### ISSUE TITLE
Massive Load, Pool does not recover. 

### ISSUE THREAD

**Issue by djerraballi** [brettwooldridge/HikariCP#315] opened 2015-05-13 19:18 UTC
Hi again, 
 I am currently load testing my application. The behavior that i am seeing is that application and pool behave fine under reasonable load. When we start ramping up however, the db connections break down. Even after stopping the load, we do not recover until we restart the server. 

I suspect that configuration for the pool/db/dns are incorrect.

Here is our DataSource config:
https://gist.github.com/djerraballi/46b46ff89f5635af1c3e

Here are the errors we start seeing when we start pushing the load up: 
https://gist.github.com/djerraballi/9ecb8e7727e3dac51769

Restarting the jetty server fixed the issue. In an earlier question, we talked about dns caching at the jvm layer. 
Here our jvm settings for network address cacheing: 
networkaddress.cache.ttl=120
networkaddress.cache.negative.ttl=10

**Comment by djerraballi** [comment] 2015-05-13 19:19
I think the 120 for cache.ttl is a little high, but we were experiencing these errors for hours until we restarted.

**Comment by djerraballi** [comment] 2015-05-13 22:30
```
{
  "currentTime" : 1431556183253,
  "poolMetrics" : {
    "result" : [ {
      "poolName" : "ReadPool",
      "totalConnections" : 15,
      "idleConnections" : 0,
      "activeConnections" : 15,
      "pendingConnections" : 750,
      "waitTimer" : {
        "count" : 232694,
        "meanRate" : 204.45689873353166,
        "oneMinuteRate" : 447.293778865452,
        "fiveMinuteRate" : 355.41715128488585,
        "fifteenMinuteRate" : 190.85484845426168,
        "snapshot" : {
          "min" : 298,
          "max" : 18584742259,
          "mean" : 1.7987148707898605E9,
          "stdDev" : 1.9706399983649473E9,
          "median" : 1.168469748E9
        }
      },
      "usage" : {
        "count" : 232682,
        "snapshot" : {
          "min" : 298,
          "max" : 18584742259,
          "mean" : 1.7987148707898605E9,
          "stdDev" : 1.9706399983649473E9,
          "median" : 1.168469748E9
        }
      }
    }
```

**Comment by brettwooldridge** [comment] 2015-05-14 00:28
Ultimately, this comes down to a DNS and/or MySQL issue, not a HikariCP issue.  As ultimately the error is "java.net.UnknownHostException: database-host.net: unknown error".

Amazon's recommended setting is 60 seconds:

http://docs.aws.amazon.com/AWSSdkDocsJava/latest//DeveloperGuide/java-dg-jvm-ttl.html

I also notice this in the stacktrace:
```
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
...
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[mysql-connector-java-5.1.33.jar:5.1.33]
```
Re: ``connectOneTryOnly()``, it may be that MySQL's driver is also giving up too quickly.  You might try the MySQL driver option [``autoReconnectForPools``](http://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html) ... though the standard ``autoReconnect`` should be avoided.

**Comment by djerraballi** [comment] 2015-05-14 00:52
That is fair, haven't been able to debug this dns thing since i haven't been able to replicate, but we did find these two settings for mysql on our jdbc url that have improved network bandwith: 
        // Removes unnecessary no-ops
        hikariConfig.addDataSourceProperty("useLocalSessionState", true);
        hikariConfig.addDataSourceProperty("useLocalTransactionState", true);

Probably not related, but still without these settings we were sending a bunch of usesless commadns over the network , and we were getting throttled quicker than we expected.

**Comment by brettwooldridge** [comment] 2015-05-14 01:05
@djerraballi Thanks for that, I'll added those to the recommended list of MySQL driver settings!

**Comment by brettwooldridge** [comment] 2015-05-14 01:08
@djerraballi Opps, didn't mean to close the issue.  Also, I did find this MySQL bug related to 'useLocalTransactionState', which is important to note:

https://bugs.mysql.com/bug.php?id=75209

**Comment by brettwooldridge** [comment] 2015-05-14 01:16
@djerraballi Looping back to your original comment:
```
When we start ramping up however, the db connections break down. Even after stopping
the load, we do not recover until we restart the server.
```
This last part is particularly troubling to me.  I understand the connections breaking down under load (given the outstanding DNS issues), however the fact that the pool does not recover once load is removed is very troubling.

Can you enable DEBUG logging for HikariCP, and maybe direct the logs for the ``com.zaxxer.hikari`` package to a separate file?  The logs aren't too chatty, and I think should not impact performance much overall.  If you can collect a log, and note about what time "trouble starts" and at what time the load is removed, I would be very interested to analyze the log.

**Comment by brettwooldridge** [comment] 2015-05-14 04:18
@djerraballi Lastly, I'd recommend upgrading to the latest release, 2.3.7 -- it contains a fix for a race condition under load, as well as a fix for an issue that prevented HikariCP from setting network timeouts on MySQL connections (which could definitely affect reliability).

**Comment by djerraballi** [comment] 2015-05-14 19:34
Hey brett, yes, we have run a few tests and noted that at times the pool took a very long time to recover.I will try 2.3.7 and test today. I can also enable debug logging and see whats up, we also have added a metrics registry, so it is easy to take a host and see the pool size, pending/active conns, and rate-meanWaitTime.

 What i suspect is that our webserver is queing incoming requests seperately from the applications internal pool (only true if server doesn't have a timeout fi the request doesn't obtain a thread). In addition to not having this timeout, i also think our jetty threadpool size is much higher than what our cp is capable of serving, so when our jetty thread pool is saturated, the requests that obtain threads will still timeout at the cp level. This is just a suspcian

good catch on useLocalTransactionState, based on the bug looks like its fixed in latest version of connectorJ? I cant tell based on the comments. but i feel like umesh is saying its fixed. 

On a side note with the network issuing:

In addition, i have been trying to reduce chattiness of our connections with the db. Connector/J provides a lot of nice features for reducing chattiness, (useConfigs=maxPeformance && useLocalTransactionState="true") but even with all the settings turned on, i am still seeing quite a few of these:
...1.../#....set session transaction read write

I have also tried to use MariaDB, and i am seeing a bit more chattiness (unexpected): 
..=...=......set autocommit=0
..=...=......SELECT @@tx_isolation
..=...=......$....def....@@tx_isolation..!.*.......................READ-COMMITTED.........

These are essentially no-ops since those settings don't change between requests. Is there a setting that basically gets us this behavior when the connection is obtained: 
```
if 
(
 con.getTransactionIsolation() !=
Connection.TRANSACTION_READ_COMMITTED
)
{
 con.setTransactionIsolation
(Connection.TRANSACTION_READ_COMMITTED);
}
```
and I found this slide deck to be super informative: 
http://www.percona.com/live/mysql-conference-2015/sites/default/files/slides/Java%20MySQL%20Connector%20%26%20Connection%20Pool%20Features%20%26%20Optimization-Version2.pdf

**Comment by brettwooldridge** [comment] 2015-05-15 01:15
I'm not sure you web server has too many threads... it should be able to have 3-5x the pool size, depending of course on query times.

Looking at the metrics you posted, the mean waitTime is around 200ms. There is clearly something wrong with the max. time calculation, so the usage metric is rather useless (again something seems to be messing with the system clock).  But the wait time and usage times should be nearly identical in a saturated pool, so no big loss.  Either way, a 200ms average query time seems rather long to me.  Have you profiled the SQL?  Double-digit query times should be a goal (single even better).

One interesting thing I found is Connector/J will ignore *useLocalTransactionState* if the query cache is enabled on the server-side.

https://github.com/michielm/GDA/blob/master/Connector/mysql-connector-java-5.1.25/src/com/mysql/jdbc/ConnectionImpl.java#L3756

Which can cause this code to always execute:

https://github.com/michielm/GDA/blob/master/Connector/mysql-connector-java-5.1.25/src/com/mysql/jdbc/ConnectionImpl.java#L5484

That doesn't seem to be happening in your case, but I can't find any other uses of "set session transaction read write".

**Comment by djerraballi** [comment] 2015-05-15 02:31
the metrics i posted were one box under heavy load, but we have quite a few boxing and only one db master, so under heavy load the average query time becomes much Higher. 

Without load we se average hovering around 2microseconds.

**Comment by jnehlmeier** [comment] 2015-05-15 12:22
From what I can tell Hikari 2.3.7 works fine under load testing (nginx + jetty + postgres cluster).

However I never tested how Hikari behaves if tons of DB connections fail because that is a situation you don't want to be in in the first place. You should tune your cluster that this never happens. That means figure out the work load your DB can handle without killing itself, then tune your connection pools to never exceed that max DB work load (your app servers should never be able to kill your DB) and finally tune your load balancers to never kill an app server by exceeding the app servers max work load.

Given that your root cause is a Java exception caused by failed DNS lookup you should fix that first. So maybe try using the IP address to connect to your DB server instead of a DNS host name. Your DB connections should not fail because of DNS issues, that is not acceptable.

**Comment by brettwooldridge** [comment] 2015-05-15 16:55
@jnehlmeier Agree with almost everything, except in their case the alter the DNS to point at a new host in the case of failure.  However, using a HA proxy or load balancer in front of the DB would probably yield a more reliable failover.

**Comment by jnehlmeier** [comment] 2015-05-15 17:32
Using DNS for DB failover sounds weird. Beside HA proxy / load balancers there is also Pacemaker on top of Heartbeat/Corosync which allows you to provide a shared IP that can move between hosts (IP failover).

But well if @djerraballi uses DNS for failover then he must make sure that DNS queries are answered within the standard timeout of linux (assuming things run on linux) even if the system has a high load (and of course do not generate more load than the system including DNS can ever handle).

By default the linux DNS timeout is 5 seconds with a retry count of 2 (see man page of resolv.conf).

**Comment by djerraballi** [comment] 2015-05-15 22:25
thanks @brettwooldridge @jnehlmeier,

I think we can resolve this. This is not a pool issue, and the solution seems to be in two parts. 

First, when the pools from all our hosts are saturated, we are being throttled at the DB level. 
That likely means we could benefit from reducing the pool size across hosts.
What i don't like about that adding or removing hosts will require change in max pool size, but that is probably not a huge worry. 
--Seems like the recommended pool size is 10 conn, but if you have 10 hosts each with their own connection pool does it make sense to reduce that? and if so how significantly? I will be running some tests with fewer hosts today to to see if this theory pans out. 

The second is solving the dns issue. @brettwooldridge  you are correct we do dns failover. We killed our db, we weren't getting up status, and dns resolution began failing for a long time. I have not been able to replicate this issue, so it is hard to test if our changes will make any difference, but i removing the noops (@@session  selects and unnecessary commits with the driver settings reduced network utilization drastically (50%)). 

All in all just want to thank both of you for your help with this issue, and @brettwooldridge  i will be following up with that useLocalTransactionState and let you know if i was able to lose the "set session transaction read write".

**Comment by brettwooldridge** [comment] 2015-05-16 06:03
@djerraballi The formula in the wiki can be thought of not as a pool size calculation but as the number of connections that the *DB can simultaneously service before performance begins to degrade*.  This is regardless of the number of client hosts or the presence of pools.  Obviously the formula provides an estimate, and the optimal value could easily be half, double, or even triple that depending on the DB vendor and configuration.

So sadly, whatever that value is, it should be divided evenly among the client hosts.  But that statement is based on the a few assumptions:
 * Client hosts are of roughly equal capability (CPU, memory)
 * Load is roughly evenly distributed among those hosts
 * The query mix is roughly similar among those hosts

If those assumptions are correct, the implication is this:
 * If, for example, indeed the DB provides peak performance at 10 client connections, and you have 5 front end hosts, it *does* imply a pool size of 2 on each host.  However, it is entirely possible that that is actually a reasonable value and provides sufficient response times.

Assuming again that you have no control over the number of requests coming into the front end, if this value is insufficient, the only real recourse is increased DB capacity (after squeezing every drop of performance out of the DB through tuning/profiling).

It also may call for a review of the application architecture.  Can some queries be avoided with a cache?

Finally, regarding dynamically adding hosts and what that means for pool sizes.  Ideally, the DB would have a certain amount of excess capacity, allowing a certain number of hosts to be added without adjusting pool sizes.  Alternatively and/or additionally a "management app" could use JMX to remotely adjust pool sizes as hosts are added/removed.

**Closed** 2015-05-20 09:15 UTC

**Comment by karlmdavis** [comment] 2018-11-29 20:30
We are now also running into a similar issue that we can reliably replicate with our load tests: we have to restart our application's service/process in order to clear a negative DNS lookup for the DB, once one has been encountered.

I'm unfortunately not able to spend a ton of time looking at this yet (due to a conference) but I've been poking around in the OpenJDK source and I'm wondering if Hikari is keeping around long-lived `InetSocketAddress` instances? Because it looks like if the DNS lookup fails when one is constructed, that object instance will never attempt re-resolution.

See http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/net/AbstractPlainSocketImpl.java#l183 for where things are going boom for us.

**Comment by brettwooldridge** [comment] 2018-12-11 16:03
@karlmdavis Set the JVM [to never cache "negative lookups"](https://docs.oracle.com/javase/7/docs/technotes/guides/net/properties.html).  Also, maybe, shorten the default DNS TTL to something like 5 seconds.

**Comment by karlmdavis** [comment] 2018-12-15 21:51
@brettwooldridge Our app's JVM is configured to only cache negative lookups for 10 seconds, yet HikariCP appears to be caching it permanently: once a lookup fails, it won't succeed again until the app/service is restarted. I'm pretty sure this is a bug in how Hikari is handling addresses, but haven't had a chance to dig too far into it yet.

**Comment by djerraballi** [comment] 2018-12-16 00:39
IIRC if the exception is being thrown in INetAddress than i honestly thing
its a bug with the JVMs negative cache. I also was not able to see anything
wrong with their code but the stack trace doesn’t lie. (Dns lookups on the
os were working when the server got into the state, so the issue was only
in the jvm). I kind of doubt its a hikari issue, if you can replicate this
consistently, add an api or cron that does a bare inetaddress lookup and
see if that works (hikaricp will be out of the picture) .
