### ISSUE TITLE
New metric to measure time to establish connections.

### ISSUE THREAD

**Issue by stottpaul** [brettwooldridge/HikariCP#769] opened 2016-11-25 13:38 UTC
Could we have a metric that measures time to establish physical DB connections, this will help us to take a view on the cost of establishing/recycling connections, which will influence decisions as to how we configure the rest of the pool.

**Comment by samhendley** [comment] 2016-11-30 22:15
I think we can probably consider this a dupe of #518. If we add a historgram type metric it would cover both the count and how long it is taking

**Comment by brettwooldridge** [comment] 2016-12-05 18:29
Fixed by 1807776.

**Closed by brettwooldridge** 2016-12-05 18:29 UTC
