### ISSUE TITLE
Connection Leak

### ISSUE THREAD

**Issue by felahi** [brettwooldridge/HikariCP#612] opened 2016-04-13 18:20 UTC
In Hikari 2.4.5, after getting lots of connection leaked exceptions, connections are not returning to pool.

       23:17:01,596 DEBUG HikariPool:logPoolState:383 - Before cleanup	pool HikariPool-0 stats      (total=29, active=24, idle=5, waiting=0)
       23:17:01,596 DEBUG HikariPool:logPoolState:383 - After cleanup	pool HikariPool-0 stats (total=29, active=24, idle=5, waiting=0)

Don't understand why these 24 connections stuck ?

**Comment by brettwooldridge** [comment] 2016-04-13 23:51
If you are leaking connections, they will never timeout and never be closed by HikariCP.  You must find the source/cause of the leak.  It could be in your application, or it could be caused by a misconfugured framework (Hibernate, Spring, etc).

**Comment by felahi** [comment] 2016-04-14 04:59
So what about these 24 connections ? When did they timeout ?

**Comment by felahi** [comment] 2016-04-14 05:12
10:08:11,849  WARN ProxyLeakTask:run:87 - Connection leak detection triggered for connection com.mysql.jdbc.JDBC4Connection@31adbd51, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.hibernate.HikariConnectionProvider.getConnection(HikariConnectionProvider.java:106)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:387)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:228)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:171)
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doBegin(JdbcTransaction.java:67)
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.begin(AbstractTransactionImpl.java:162)
	at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1435)
	at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:61)
	at com.careem.backend.persistence.TripRepository.getTripCount(TripRepository.java:138)
	at com.careem.backend.action.CBUserProfileAction.execute(CBUserProfileAction.java:39)
	at com.careem.controller.http.CBUserController.getUserProfile(CBUserController.java:29)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.togglz.servlet.TogglzFilter.doFilter(TogglzFilter.java:100)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2500)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by felahi** [comment] 2016-04-14 05:23
@brettwooldridge so what parameter should be configured correctly in order to avoid this ?


           <property name="hibernate.hikari.connectionTimeout" value="30000" />

Is this property creating a mess due to less timeout value ?

**Comment by felahi** [comment] 2016-04-14 07:05
@brettwooldridge Yes u r right. 

         tx.begin();

throws an exception

**Comment by felahi** [comment] 2016-04-14 07:07
But in C3P0 if connection leak occurs, there is a property "unreturnedConnectionTimeout" which forcefully close the leaked connection.

**Comment by brettwooldridge** [comment] 2016-04-14 09:09
HikariCP does not, in principle, believe that the pool should coverup connection leaks.  We disagree with the reasoning behind C3P0's unreturned connection handling.

The leak detection is there to help you pinpoint the source of the leak.  That should provide enough clues to track down the configuration or coding error.

**Comment by brettwooldridge** [comment] 2016-04-14 09:11
Follow this thread http://stackoverflow.com/questions/27925914/spring-or-hibernate-connection-leak

**Closed by brettwooldridge** 2016-04-14 09:11 UTC

**Comment by brettwooldridge** [comment] 2016-04-14 09:25
This might also help https://jira.spring.io/plugins/servlet/mobile#issue/SPR-13269
