### ISSUE TITLE
connection leak

### ISSUE THREAD

**Issue by wplatform** [brettwooldridge/HikariCP#718] opened 2016-09-13 10:33 UTC
If get/close connection is not the same thread ,the connection will leak

//threadLocal differences , so the connection not return the pool,
public void requite(final T bagEntry)
   {
      bagEntry.lazySet(STATE_NOT_IN_USE);
      final List<Object> threadLocalList = threadList.get();
      if (threadLocalList != null) {
         threadLocalList.add(weakThreadLocals ? new WeakReference<>(bagEntry) : bagEntry);
      }
      synchronizer.signal();
   }

**Comment by brettwooldridge** [comment] 2016-09-13 17:38
@wplatform That is not a leak.  It just means that the returned Connection is put in the ThreadLocal list of the *closing* thread.  This means that your code misses out on an important optimization, but it does not leak, because there is a separate master list.

Basically, when a thread calls ``getConnection()``, it calls ``ConcurrentBag.borrow()``, which will first attempt to get an unused connection from that thread's ``ThreadLocal`` list of recently used connections.  In your case, that list will never contain the recently closed connections, so the thread will then scan the master list of connections.  This is less efficient, but still correct.

The bug you are experiencing is likely caused by ``bagEntry.lazySet(STATE_NOT_IN_USE)``.  This uses the ``AtomicInteger.lazySet()`` method, which has memory side-effects that can cause the state change to not be immediately visible to other threads.  The change I made for #716 should address that problem.

**Closed by brettwooldridge** 2016-09-13 17:38 UTC

**Comment by wplatform** [comment] 2016-09-17 16:42
@brettwooldridge Thank you for your reply. I tried to put getConnect() /close() on same thread, but the performance is not very good, I need to find out why.

**Comment by brettwooldridge** [comment] 2016-09-18 07:48
@wplatform You might try configuring another pool, C3P0 or Apache DBCP for example, to see if you observe similar behavior/performance.  I don't think returning on the same thread or different thread will make that much of a performance difference in general, unless you are running thousands of transactions/sec.  The difference is likely in the hundreds of nanoseconds on getConnection() and no difference on close().

**Comment by wplatform** [comment] 2016-09-27 01:17
HikariCP performance is the best.

**Comment by wplatform** [comment] 2016-09-27 03:58
How do I optimize my program, I changed the code, the closed and open operation in the same thread, but I am less than before the TPS by half, many threads waiting on the lock for ConcurrentBag.borrow

Stack Trace	Longest	Count
sun.misc.Unsafe.park(boolean, long)	29,999,726,750	547,896
   java.util.concurrent.locks.LockSupport.parkNanos(Object, long)	29,999,726,750	522,145
      java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(long)	29,999,726,750	516,121
      java.util.concurrent.locks.AbstractQueuedLongSynchronizer.doAcquireSharedNanos(long, long)	53,469,929	6,024
         java.util.concurrent.locks.AbstractQueuedLongSynchronizer.tryAcquireSharedNanos(long, long)	53,469,929	6,024
            com.zaxxer.hikari.util.QueuedSequenceSynchronizer.waitUntilSequenceExceeded(long, long)	53,469,929	6,024
               com.zaxxer.hikari.util.ConcurrentBag.borrow(long, TimeUnit)	53,469,929	6,024
                  com.zaxxer.hikari.pool.HikariPool.getConnection(long)	53,469,929	6,024

**Comment by rafaliwaniak** [comment] 2017-06-09 10:09
@wplatform Hi, did you solve your problem? I've got the same issue with my Hikari pooling...

**Comment by 13821042128** [comment] 2023-06-21 07:16
我也遇到了同样的问题（java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000002da5436f8> (a java.util.concurrent.SynchronousQueue$TransferQueue)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferQueue.awaitFulfill(SynchronousQueue.java:764)
	at java.util.concurrent.SynchronousQueue$TransferQueue.transfer(SynchronousQueue.java:695)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)），请问你们解决了吗？
