### ISSUE TITLE
Connection was marked as broken because of SQLSTATE(08006), ErrorCode(17002)  thrown with IO Error: Operation timed out

### ISSUE THREAD

**Issue by Betternan** [brettwooldridge/HikariCP#1569] opened 2020-04-13 04:04 UTC
**Version**:
springboot: 2.0.2.RELEASE
HikariCP: 3.4.0
ojdbc8: 12.2.0.1
Mybatis: 3.4.0
mybatis-spring: 1.3.0

**Hikari Configuration:**
```
Hikari - configuration:
: allowPoolSuspension.............false
: autoCommit......................true
: catalog.........................none
: connectionInitSql...............none
: connectionTestQuery............."SELECT 1 FROM DUAL"
: connectionTimeout...............600000
: dataSource......................none
: dataSourceClassName.............none
: dataSourceJNDI..................none
: dataSourceProperties............{password=<masked>, prepStmtCacheSqlLimit=2048, cachePrepStmts=true, prepStmtCacheSize=250}
: driverClassName................."oracle.jdbc.driver.OracleDriver"
: healthCheckProperties...........{}
: healthCheckRegistry.............none
: idleTimeout.....................600000
: initializationFailTimeout.......5000
: isolateInternalQueries..........false
: jdbcUrl.........................jdbc:oracle:thin:@
: leakDetectionThreshold..........0
: maxLifetime.....................1800000
: maximumPoolSize.................10
: metricRegistry..................none
: metricsTrackerFactory...........none
: minimumIdle.....................5
: readOnly........................false
: registerMbeans..................false
: scheduledExecutor...............none
: schema..........................none
: threadFactory...................internal
: transactionIsolation............default
: validationTimeout...............5000
```

This exception is thrown when try to do the lots of insert operations, hundreds of data among 10 tables around. Also this operation occurred in the application initialed and the transaction was controlled with Spring @Transactinal.

Stack trace:
```
Hikari Pool-Data_Visualization_Service - Thread starvation or clock leap detected (housekeeper delta=2m20s593ms).
2020-04-04 01:52:02.648 DEBUG 7202 --- [ice housekeeper] com.zaxxer.hikari.pool.HikariPool        : Hikari Pool-Data_Visualization_Service - Before cleanup stats (total=6, active=1, idle=5, waiting=0)
2020-04-04 01:55:57.549 DEBUG 7202 --- [Engine[Tomcat]]] org.apache.catalina.session.ManagerBase  : Start expire sessions StandardManager at 1585936306922 sessioncount 0
2020-04-04 01:55:57.550 DEBUG 7202 --- [ice housekeeper] com.zaxxer.hikari.pool.HikariPool        : Hikari Pool-Data_Visualization_Service - After cleanup  stats (total=6, active=1, idle=5, waiting=0)
2020-04-04 01:55:57.550 DEBUG 7202 --- [Engine[Tomcat]]] org.apache.catalina.session.ManagerBase  : End expire sessions StandardManager processingTime 250628 expired sessions: 0
2020-04-04 01:56:29.397  WARN 7202 --- [ice housekeeper] com.zaxxer.hikari.pool.HikariPool        : Hikari Pool-Data_Visualization_Service - Thread starvation or clock leap detected (housekeeper delta=4m42s474ms).
2020-04-04 01:56:29.397 DEBUG 7202 --- [ice housekeeper] com.zaxxer.hikari.pool.HikariPool        : Hikari Pool-Data_Visualization_Service - Before cleanup stats (total=6, active=1, idle=5, waiting=0)
2020-04-04 01:56:29.399 DEBUG 7202 --- [ice housekeeper] com.zaxxer.hikari.pool.HikariPool        : Hikari Pool-Data_Visualization_Service - After cleanup  stats (total=6, active=1, idle=5, waiting=0)
2020-04-04 01:57:00.831 DEBUG 7202 --- [ice housekeeper] com.zaxxer.hikari.pool.HikariPool        : Hikari Pool-Data_Visualization_Service - Before cleanup stats (total=6, active=1, idle=5, waiting=0)
2020-04-04 01:57:00.832 DEBUG 7202 --- [ice housekeeper] com.zaxxer.hikari.pool.HikariPool        : Hikari Pool-Data_Visualization_Service - After cleanup  stats (total=6, active=1, idle=5, waiting=0)
2020-04-04 01:57:00.835  WARN 7202 --- [           main] com.zaxxer.hikari.pool.ProxyConnection   : Hikari Pool-Data_Visualization_Service - Connection oracle.jdbc.driver.T4CConnection@22d8f4ed marked as broken because of SQLSTATE(08006), ErrorCode(17002)

java.sql.SQLRecoverableException: IO Error: Operation timed out
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:932) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.4.0.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) [HikariCP-3.4.0.jar:na]
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59) [mybatis-3.4.0.jar:3.4.0]
	at com.sun.proxy.$Proxy110.execute(Unknown Source) [na:na]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46) [mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) [mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50) [mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) [mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) [mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198) [mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185) [mybatis-3.4.0.jar:3.4.0]
	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434) [mybatis-spring-1.3.0.jar:1.3.0]
	at com.sun.proxy.$Proxy81.insert(Unknown Source) [na:na]
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:279) [mybatis-spring-1.3.0.jar:1.3.0]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:56) [mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53) [mybatis-3.4.0.jar:3.4.0]
	at com.sun.proxy.$Proxy94.saveChartInfo(Unknown Source) [na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365) [spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308) [spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135) [spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) [spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1698) [spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579) [spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501) [spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) [spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) [spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at RunApplication.main(RunApplication.java:13) ~[classes/:na]
Caused by: java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_121]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_121]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_121]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_121]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_121]
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:144) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.net.ns.NIOHeader.readHeaderBuffer(NIOHeader.java:82) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:139) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:101) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:80) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForReading(T4CMAREngineNIO.java:98) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:534) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:485) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:910) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	... 76 common frames omitted

2020-04-04 01:57:00.836 DEBUG 7202 --- [nnection closer] com.zaxxer.hikari.pool.PoolBase          : Hikari Pool-Data_Visualization_Service - Closing connection oracle.jdbc.driver.T4CConnection@22d8f4ed: (connection is broken)
2020-04-04 01:57:00.838 DEBUG 7202 --- [           main] org.mybatis.spring.SqlSessionUtils       : Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@673a5aa7]
2020-04-04 01:57:00.838 DEBUG 7202 --- [           main] o.s.jdbc.datasource.DataSourceUtils      : Returning JDBC Connection to DataSource
```

I also tried with the maxpoolsize 20, but the issue are the same.

**Comment by Allenlebron** [comment] 2020-04-17 10:50
Bro Is the problem solved?

**Comment by wang-xu-huai** [comment] 2020-04-17 10:54
I have a similar problem. It is the connection reset and the prompt will be printed when I start the app

HikariPool-1 - Driver does not support get/set network timeout for connections. (oracle.jdbc.driver.T4CConnection.getNetworkTimeout()I)
2020-04-17 16:55:12,122 WARN  c.z.hikari.pool.ProxyConnection - HikariPool-1 - Connection oracle.jdbc.driver.T4CConnection@546ccad7 marked as broken because of SQLSTATE(08006), ErrorCode(17002) java.sql.SQLRecoverableException: IO Error: Connection reset

Have you solved this problem? I doubt that the Oracle driver version does not support it. If you want to change the driver version, which version can support it

**Comment by quaff** [comment] 2020-04-26 09:58
I think this is acceptable, if you want to change the default behavior, please see https://github.com/brettwooldridge/HikariCP/commit/a51e6a07e856db5f0bce969d83126a0e4dad676a

**Comment by Betternan** [comment] 2020-04-29 12:50
@quaff ,  thanks for yours clue. But why this exception is thrown? It's not the root cause, the application couldn't do anything on DB with this exception. Is there any config param setting for this exception?

**Comment by Betternan** [comment] 2020-04-29 12:54
@Allenlebron , @uwolfer it's still not be fixed here.

**Comment by quaff** [comment] 2020-04-29 23:52
@Betternan You should investigate why `java.io.IOException: Operation timed out` is thrown, maybe caused by network or DB is busy, and you should avoid large transaction.

**Comment by wang-xu-huai** [comment] 2020-04-30 00:12
@Betternan I am wrong with the problem you encountered. My reason is that the entropy pool of the host where the database application is located is exhausted. You can refer to it.

**Comment by Betternan** [comment] 2020-05-07 07:32
@quaff , your reminder is correct, the app indeed has a large transaction, but this transaction couldn't be split

**Comment by Betternan** [comment] 2020-05-07 07:34
@wang-xu-huai ,thanks for your help. I'll check with DBA for this. Do you work against Oracle DB?

**Closed as completed** 2020-05-08 13:14 UTC
