### ISSUE TITLE
Tomcat parsing error since 2.3.x

### ISSUE THREAD

**Issue by Adhara3** [brettwooldridge/HikariCP#248] opened 2015-01-30 11:57 UTC
Hi,

I know this issue is more related to Javassist 3.19, but I was wondering if this is an issue that could come from the fact that you are trying to keep both java6/8 version updated.

With Hikari 2.2.5 (javassist 3.18.1), starting in tomcat 8.0.9 java 7 works great.
With Hikari 2.3.x (javassist 3.19), starting in tomcat 8.0.9 java 7 produces n errors like the following, one for each file.

    30-Jan-2015 12:46:46.055 SEVERE [http-nio-9080-exec-1]     org.apache.catalina.startup.ContextConfig.processAnnotationsJar Unable to process Jar entry [javassist/util/proxy/SerializedProxy.class] from Jar [jar:file:/D:/Tomcat8/xxxxxxx/javassist-3.19.0-GA.jar!/] for annotations
 java.io.EOFException

Sometimes this brings to outofmemory exception.

Have you an idea of why this is happening? Did you experience the same somehow?

Thanks
Andrea

**Comment by Adhara3** [comment] 2015-01-30 11:59
I wonder if this is somehow related to [this](https://groups.google.com/forum/#!topic/hikari-cp/86CgV9PUCJI)

**Comment by brettwooldridge** [comment] 2015-01-30 12:29
@Adhara3 I'm not sure what is up with Tomcat 8.0.9 + Java 8, but I do not think it is related to HikariCP.  This bug in their database Shows and almost identical error:

https://issues.apache.org/bugzilla/show_bug.cgi?id=57251
```
24-Nov-2014 13:37:44.119 SEVERE [localhost-startStop-1] org.apache.catalina.startup.ContextConfig.processAnnotationsJar Unable to process Jar entry [com/google/cloud/sql/jdbc/internal/ConnectionProperty.class]
from Jar [jar:file:/C:/Programs/apache-tomcat-8.0.15/webapps/ROOT.war!/WEB-INF/lib/appengine-api-1.0-sdk-1.9.10.jar] for annotations
java.io.EOFException
```

**Comment by brettwooldridge** [comment] 2015-01-30 13:14
This bug is actually more relevant https://issues.apache.org/bugzilla/show_bug.cgi?id=57173

**Comment by brettwooldridge** [comment] 2015-01-30 13:17
Comment 16 seems to imply that the issue is fixed in Tomcat 8.0.16+

https://issues.apache.org/bugzilla/show_bug.cgi?id=57173#c16

**Closed by brettwooldridge** 2015-01-30 13:17 UTC
Labels: question

**Comment by Adhara3** [comment] 2015-01-30 16:38
Yes, as I suspected, it was a Tomcat/Javassist issue.
I was just wondering if you had any other feedback on this.

Thank you very much for your help.

Andrea

**Comment by aug828** [comment] 2015-02-09 22:28
I used to have this problem. Switched to tomcat 8.0.18 and problem disappeared.

**Comment by brettwooldridge** [comment] 2015-02-10 01:02
@aug828 thanks for the confirmation.
