### ISSUE TITLE
idleTimeout does not appear to be being honoured

### ISSUE THREAD

**Issue by stottpaul** [brettwooldridge/HikariCP#657] opened 2016-06-28 14:49 UTC
I've written a small test class which simply sets up a Hikari CP 2.4.6 with an idleTimeout and a maxLifetime and a MaximumPoolSize of 4. The program then just goes into an empty loop.   

The logging suggests that connections are being closed due to maxLifetime instead of idleTimeout.

**Code extract**

```
HikariConfig config = new HikariConfig();
        
config.setJdbcUrl(LOCAL_XE_CONN_STRING);
config.setUsername("system");
config.setPassword("oracle");
config.setIdleTimeout(40000);
config.setMaxLifetime(100000);
config.setMaximumPoolSize(4);

new HikariDataSource(config);

while(true);
```

**Debug logs**
2016-06-28 15:36:26 DEBUG HikariConfig:839 - HikariPool-1 - configuration:
2016-06-28 15:36:26 DEBUG HikariConfig:855 - allowPoolSuspension.............false
2016-06-28 15:36:26 DEBUG HikariConfig:855 - autoCommit......................true
2016-06-28 15:36:26 DEBUG HikariConfig:855 - catalog.........................null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - connectionInitSql...............null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - connectionTestQuery.............null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - connectionTimeout...............30000
2016-06-28 15:36:26 DEBUG HikariConfig:855 - dataSource......................null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - dataSourceClassName.............null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - dataSourceJNDI..................null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - dataSourceProperties............{password=<masked>}
2016-06-28 15:36:26 DEBUG HikariConfig:855 - driverClassName.................null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - healthCheckProperties...........{}
2016-06-28 15:36:26 DEBUG HikariConfig:855 - healthCheckRegistry.............null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - idleTimeout.....................**40000**
2016-06-28 15:36:26 DEBUG HikariConfig:855 - initializationFailFast..........true
2016-06-28 15:36:26 DEBUG HikariConfig:855 - isolateInternalQueries..........false
2016-06-28 15:36:26 DEBUG HikariConfig:855 - jdbc4ConnectionTest.............false
2016-06-28 15:36:26 DEBUG HikariConfig:855 - jdbcUrl........................."jdbc:oracle:thin:@192.168.99.100:1521:xe"
2016-06-28 15:36:26 DEBUG HikariConfig:855 - leakDetectionThreshold..........0
2016-06-28 15:36:26 DEBUG HikariConfig:855 - maxLifetime.....................**100000**
2016-06-28 15:36:26 DEBUG HikariConfig:855 - maximumPoolSize.................4
2016-06-28 15:36:26 DEBUG HikariConfig:855 - metricRegistry..................null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - metricsTrackerFactory...........null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - minimumIdle.....................4
2016-06-28 15:36:26 DEBUG HikariConfig:855 - password........................<masked>
2016-06-28 15:36:26 DEBUG HikariConfig:855 - poolName........................"HikariPool-1"
2016-06-28 15:36:26 DEBUG HikariConfig:855 - readOnly........................false
2016-06-28 15:36:26 DEBUG HikariConfig:855 - registerMbeans..................false
2016-06-28 15:36:26 DEBUG HikariConfig:855 - scheduledExecutorService........null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - threadFactory...................null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - transactionIsolation............null
2016-06-28 15:36:26 DEBUG HikariConfig:855 - username........................"system"
2016-06-28 15:36:26 DEBUG HikariConfig:855 - validationTimeout...............5000
2016-06-28 15:36:26 INFO  HikariDataSource:70 - HikariPool-1 - Started.
2016-06-28 15:36:27 INFO  PoolBase:444 - HikariPool-1 - Driver does not support get/set network timeout for connections. (oracle.jdbc.driver.T4CConnection.getNetworkTimeout()I)
2016-06-28 15:36:27 DEBUG HikariPool:391 - HikariPool-1 - Pool stats (total=0, active=0, idle=0, waiting=0)
2016-06-28 15:36:27 DEBUG HikariPool:458 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@92dde85
2016-06-28 15:36:27 DEBUG HikariPool:458 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@5f305afa
2016-06-28 15:36:27 DEBUG HikariPool:458 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@6adc182e
2016-06-28 15:36:27 DEBUG HikariPool:458 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@31530097
2016-06-28 15:36:27 DEBUG HikariPool:391 - HikariPool-1 - After adding stats (total=4, active=0, idle=4, waiting=0)
2016-06-28 15:36:57 DEBUG HikariPool:391 - HikariPool-1 - Pool stats (total=4, active=0, idle=4, waiting=0)
2016-06-28 15:37:27 DEBUG HikariPool:391 - HikariPool-1 - Pool stats (total=4, active=0, idle=4, waiting=0)
2016-06-28 15:37:57 DEBUG HikariPool:391 - HikariPool-1 - Pool stats (total=4, active=0, idle=4, waiting=0)
**2016-06-28 15:38:05 DEBUG PoolBase:111 - HikariPool-1 - Closing connection oracle.jdbc.driver.T4CConnection@5f305afa: (connection has passed maxLifetime)
2016-06-28 15:38:05 DEBUG PoolBase:111 - HikariPool-1 - Closing connection oracle.jdbc.driver.T4CConnection@6adc182e: (connection has passed maxLifetime)
2016-06-28 15:38:06 DEBUG PoolBase:111 - HikariPool-1 - Closing connection oracle.jdbc.driver.T4CConnection@92dde85: (connection has passed maxLifetime)
2016-06-28 15:38:06 DEBUG PoolBase:111 - HikariPool-1 - Closing connection oracle.jdbc.driver.T4CConnection@31530097: (connection has passed maxLifetime)**
2016-06-28 15:38:27 DEBUG HikariPool:391 - HikariPool-1 - Pool stats (total=0, active=0, idle=0, waiting=0)
2016-06-28 15:38:27 DEBUG HikariPool:458 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@6aa2d9a6
2016-06-28 15:38:27 DEBUG HikariPool:458 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@64653a82
2016-06-28 15:38:27 DEBUG HikariPool:458 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@605ab2d6
2016-06-28 15:38:27 DEBUG HikariPool:458 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@59cbb25d
2016-06-28 15:38:27 DEBUG HikariPool:391 - HikariPool-1 - After adding stats (total=4, active=0, idle=4, waiting=0)
2016-06-28 15:38:57 DEBUG HikariPool:391 - HikariPool-1 - Pool stats (total=4, active=0, idle=4, waiting=0)

**Comment by brettwooldridge** [comment] 2016-06-28 15:32
@stottpaul This is basically a documentation bug.

When running as a fixed-size pool (*default*) the ``idleTimeout`` has no effect.  Your example is a fixed-size pool -- when ``minimumIdle`` is not defined it defaults to ``maximumPoolSize``.

``idleTimeout`` is meant to shrink the pool from ``maximumPoolSize`` down toward ``minimumIdle`` when connections are unused in the pool.  However, when ``minimumIdle == maximumPoolSize`` then closing an "idle" connection makes no sense as it will be replaced immediately in the pool.

**Closed by brettwooldridge** 2016-06-28 15:32 UTC
Labels: bug

**Comment by stottpaul** [comment] 2016-06-28 16:24
Many thanks Brett, that makes perfect sense.

**Comment by azitabh** [comment] 2016-12-20 18:05
@brettwooldridge Shouldn't connections be rechecked/reconnected once they near ``maxIdleTime`` irrespective of whether the total connection count is more or less than minimumIdle value... i am coming from ``c3p0`` background and i always set this value slightly less than the mysql ``wait_timeout`` value to ensure that I don't get ``mysql has gone away`` exception... we have a situation where the app sees fluctuating traffic and mysql mandates a smaller(300 s) ``wait_timeout``... we want to ensure there are no exceptions, and we want to have a few(10) connections in idle state at the same time... only way to do so seems to be to keep a low(250s) ``maxLifetime`` value, but that would reconnect even if there is consistent activity in between... less efficient at peak load time, isn't it?

**Comment by brettwooldridge** [comment] 2016-12-21 11:19
@azitabh I'm still not clear on what the issue is.  If you set ``idleTimeout`` to 30s less than ``wait_timeout`` (35s would be safer, given that the pool is swept *approximately* every 30s), then a ``mysql has gone away`` exception should never reach your application code.  The value of ``maxLifetime`` doesn't some into play.

**Comment by azitabh** [comment] 2016-12-22 12:43
@brettwooldridge you are right in saying that `mysql has gone away` never reaches the application(it's a `c3p0` phenomenon), but invalidation of connections does happen inside the `hikaricp library` at the time of checkout of connection... here is the scenario:

    hikari.properties

    connectionTimeout=1000
    idleTimeout=250000
    minimumIdle=10
    maximumPoolSize=100
    maxLifetime=28800000
    leakDetectionThreshold=2000

mysql `wait_timeout` is set to 300 seconds... when application comes up, i see 10 connections in `hikari pool log` as well as in `mysql processlist`, if no request comes in next 300 seconds, mysql closes all 10 connections... hikaricp at the moment is seemingly unaware of this... it keeps adding the following in logs:

    [13:03:43.317 HikariPool-1 housekeeper DEBUG com.zaxxer.hikari.pool.HikariPool:391] HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)

If a fresh request comes at this moment, pool checks the connections one by one and finally creates a new connection and supplies it... so this, IMO, violates the guarantee `minimumIdle` should provide, i.e. to always keep 10 connections in ready state

**Comment by brettwooldridge** [comment] 2016-12-22 19:28
@azitabh Ah, I see it now, you are actually hitting an edge case, related to #379.  Originally, if you set an ``idleTimeout`` of 250s, then *any* connection that was idle for 250s would be retired -- even if that retirement brought the number of connections *below* ``minimumIdle`` temporarily.

I was swayed by the arguments of several users that allowing the pool to dip below ``minimumIdle`` could cause issues during spikes.  Therefore, retiring idle connections is stopped when the pool size shrinks to ``minimumIdle``, even if there are idle connections in excess of `` idleTimeout``.  However, all of that reasoning was based on the fact that ``wait_timeout`` and ``maxLifetime`` were probably set to 30 minutes or more (I think the default ``wait_timeout`` is 8 hours or something).

Tell me again why you need a ``wait_timeout`` of only 300s?

**Comment by azitabh** [comment] 2016-12-26 07:05
@brettwooldridge why `wait_timeout` has to be as low as 300s is a entirely different question... in my scenario, it is so to block connection leak because of some legacy application which doesn't close connections on it's own...

in the context of #379 , better thing to do should be to close the connection and recreate it to keep the level of `minimumIdle` maintained... `c3p0` does the same... what's your thought?
