### ISSUE TITLE
URGENT: Unusual system clock change detected, soft-evicting connections from pool.

### ISSUE THREAD

**Issue by victropolis** [brettwooldridge/HikariCP#559] opened 2016-01-26 17:59 UTC
Brett,

I saw a ton of connections from a particular host last night...

```
dgcs=# select distinct usename, application_name, client_addr, count(*) from pg_stat_activity where client_addr = '10.101.152.33' group by  usename, application_name, client_addr order by client_addr, usename;
     usename      | application_name |  client_addr  | count 
------------------+------------------+---------------+-------
 analytics_rw     |                  | 10.101.152.33 |   289
 catalog_rw       |                  | 10.101.152.33 |   192
 dgwatch_rw       |                  | 10.101.152.33 |    40
 member_rw        |                  | 10.101.152.33 |   508
 wps_processor_rw |                  | 10.101.152.33 |   200
(5 rows)
```

This morning, come to find the following in the log files every hour or so...

```
2016-01-25 21:09:15,498 WARN  [a3808e51-ff45-4d72-b5de-7efdd973ec27] [Hikari housekeeper (pool 1-MemberConnectionPool)] [pool.HikariPool] - 1-MemberConnectionPool - Unusual system clock change detected, soft-evicting connections from pool.
2016-01-25 21:09:17,948 WARN  [a3808e51-ff45-4d72-b5de-7efdd973ec27] [Hikari housekeeper (pool 2-AnalyticsConnectionPool)] [pool.HikariPool] - 2-AnalyticsConnectionPool - Unusual system clock change detected, soft-evicting connections from pool.
2016-01-25 22:09:44,837 WARN  [a3808e51-ff45-4d72-b5de-7efdd973ec27] [Hikari housekeeper (pool 1-MemberConnectionPool)] [pool.HikariPool] - 1-MemberConnectionPool - Unusual system clock change detected, soft-evicting connections from pool.
2016-01-25 22:09:47,267 WARN  [a3808e51-ff45-4d72-b5de-7efdd973ec27] [Hikari housekeeper (pool 2-AnalyticsConnectionPool)] [pool.HikariPool] - 2-AnalyticsConnectionPool - Unusual system clock change detected, soft-evicting connections from pool.
2016-01-25 23:10:45,845 WARN  [a3808e51-ff45-4d72-b5de-7efdd973ec27] [Hikari housekeeper (pool 1-MemberConnectionPool)] [pool.HikariPool] - 1-MemberConnectionPool - Unusual system clock change detected, soft-evicting connections from pool.
2016-01-25 23:10:48,285 WARN  [a3808e51-ff45-4d72-b5de-7efdd973ec27] [Hikari housekeeper (pool 2-AnalyticsConnectionPool)] [pool.HikariPool] - 2-AnalyticsConnectionPool - Unusual system clock change detected, soft-evicting connections from pool.
```

These are my configs:

```
<maxLifetime>1800000</maxLifetime>
<idleTimeout>600000</idleTimeout>
<mininumPoolSize>5</mininumPoolSize>
<maximumPoolSize>100</maximumPoolSize>
<connectionTimeout>30000</connectionTimeout>
<validationTimeout>5000</validationTimeout>
```

What is causing this?  And, what exactly is soft-evicting?  Does that fail to close the original connections?

Thanks!

**Comment by jnehlmeier** [comment] 2016-01-26 21:35
The warning states your system clock has changed by an unusual amount of time (either backwards or into the future). This can happen when you update the system clock manually or using NTP and the clock drifted too much away from the real time.
Also, there was a bug in an older version of HikariCP which prevented HikariCP from recovering from that state and thus every time HikariCP's HouseKeeper Thread had run, connections had been soft-evicted again. So if you are not using the newest version of HikariCP I would recommend to update the library and then you should check whats up with your system clock.

soft-eviction itself means that HikariCP either closes the connection immediately if it is not handed out to the application or only marks it for eviction so HikariCP can evict it later when the connection has been returned to the pool again. If a connection is only marked, eviction happens on pool.getConnection() calls so it should happen naturally over time based on your pool usage.

After a rather quick look at the code it seems like the pool should not go rogue and suddenly create more connections than usual when the soft-eviction log appears because of system clock issues. But since your `maximumPoolSize` is set to `100` you might want to check how your application code behaves when the system clock suddenly changes by a larger amount (maybe even backwards). Maybe your application then simply starts to do more stuff which causes HikariCP to build up more physical connections to your DB to handle the getConnection() pressure.

**Comment by victropolis** [comment] 2016-01-26 21:54
I'm on the latest version 2.4.3.

**Comment by victropolis** [comment] 2016-01-26 22:19
Also, the machine was just sitting idle all night.  Nothing going on on it.

**Comment by jnehlmeier** [comment] 2016-01-26 22:54
@victropolis Just to be complete: the log output can also occur if the JVM hangs for more than a minute (more precise: `2 * house keeper thread period` in case you have configured your own period). But if the machine was idle thats probably not the case.

The code is pretty simple, you can see it here: https://github.com/brettwooldridge/HikariCP/blob/HikariCP-2.4.3/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L601

If it continues to happen you may want to turn on DEBUG logging. Don't be afraid, HikariCP does not log a lot more when going down to DEBUG level.

**Comment by victropolis** [comment] 2016-01-27 06:29
Is it possible that the following is not closing the connections, but only marking them as evicted?  It's being called with owner = false.

```
   private void softEvictConnection(final PoolEntry poolEntry, final String reason, final boolean owner)
   {
      if (owner || connectionBag.reserve(poolEntry)) {
         closeConnection(poolEntry, reason);
      }
      else {
         poolEntry.markEvicted();
      }
   }
```

**Comment by brettwooldridge** [comment] 2016-01-27 08:08
@victropolis As a result of this issue, we're going to improve the logging of this message to reflect how much and in which direction the system clock shifted.

Regarding "soft eviction", you are correct that *some* connections are only being *marked* for eviction --  those that are *in-use*.  Connections that are not in-use (i.e. idle) are closed immediately.  Closing an *in-use* connection would disrupt a transaction in-progress, which is not our intent.

The issue is, when the system clock jumps backward or too far forward, we can no longer rely on our calculations for idle time, lifetime, or various timeouts.  So, we want to clear all connections created before the time-rift.  But as I said above, we do not want to disrupt in-use Connections.  Connections that are in-use will eventually be returned to the pool -- if they are not that is a different problem, an application-level connection leak -- and when they do return they will be evicted (closed).

We cannot know in this case whether the clock drifted backward or jumped forward.  Improved logging will help us to understand the magnitude of changes.

Currently, if the clock drifts backward *at all* we evict connections.  If the clock jumps forward by more than one minute, we also evict connections.  As @jnehlmeier mentioned, NTP might adjust time in the negative direction.  It is possible HikariCP needs to tolerate minor backward time movement if NTP is causing micro-second or nano-second *backward* adjustments -- and only evict connections if the millisecond threshold is crossed.

**Comment by victropolis** [comment] 2016-01-27 15:34
Brett, thanks for the comment, but I don't necessarily agree with this issue being closed just yet.  Thankfully, this happened on a development laptop.  If this happens in production, this could have harmful effects if postgres runs out of connection slots.  How is it possible to go from 15 member_rw connections (3 wars each with a min 5 connection datasource) to 508 member_rw connections on a machine that's sitting idle?

**Comment by brettwooldridge** [comment] 2016-01-27 15:43
I will reopen pending further investigation.  If you can reproduce it with DEBUG logging enabled, it would be extremely useful.

**Comment by victropolis** [comment] 2016-01-28 03:25
Thanks @brettwooldridge .  I'm slammed right now for a deadline, but I'll try to get with him to enable to the extra logging.  In the meantime, looks like it happened again.

<img width="369" alt="screen shot 2016-01-27 at 8 19 06 pm" src="https://cloud.githubusercontent.com/assets/359170/12634128/1be35ebc-c534-11e5-9e38-7a5b524ab66b.png">

**Comment by brettwooldridge** [comment] 2016-01-28 04:45
@victropolis If you're running on a laptop there are a lot of things that can happen.  Some operating systems rely on the CPU TSC (Time Stamp Counter) for high-resolution time measurements, but the TSC can be affected by power-saving modes providing unreliable time stamps as the computer transitions in and out of power-saving levels.

Power saving modes on laptops also affect the network stack, disabling the NIC without actually disconnecting sessions, and then coming back alive at some later time.  This can wreak havoc on applications.

Finally, power saving levels throttle CPU and disable cores, at more aggressive levels as the processor enters deeper levels of sleep.

| How is it possible to go from 15 member_rw connections (3 wars each with a min 5 connection
| datasource) to 508 member_rw connections on a machine that's sitting idle?

I could imagine several scenarios.  The DEBUG log will shed more light.  Here is one possible scenario:

Your pools are configured for 100 max. connections.  This is [extremely high](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing) by the way.  Between three pools it is clear that 300 connections are theoretically possible, right?

Your pools also have an idle timeout of 5 min. and a max. lifetime of 30 min.  Let's say that each pool has 5 connections, and the pool is truly idle.  HikariCP will not evict the 5 connections due to idleness, because that would bring the pool below *minimumIdle*, but it *will* evict them when they reach *maxLifetime*, and will evict them if the system clock goes backwards by more than 30 seconds or jumps forward by more than 1 minute.

Clearly we recorded unusual time motion, so evictions occurred.  My current theory is that the process/thread was starved either due to sleep or some other event (virus scan, etc.)  This would appear as a time leap forward to HikariCP.

Once evictions have occurred, HikariCP will try to refill the pool to maintain *minimumIdle*.  If there are 0 connections, then 5 "add connection" tasks will be enqueued.  This happens on a separate thread from the housekeeper.  If, for whatever reason, connections are *not* added by the time the housekeeper runs again (in 30 seconds), refill is called again.  5 more "add connection" events are added to the queue.

If this continues, meaning either 1) the starvation of threads, or 2) something preventing Connection creation, the queue of "add connection" tasks will reach *maximumPoolSize* before it starts dropping requests to queue tasks.  Eventually, if the (system wakes up|starvation ends|connectivity is restored) it will blast through the queue and create *maximumPoolSize* of "pent-up" add connection requests.

That is one theoretical scenario.  Might I suggest running some other monitoring software on the laptop/server to measure CPU, disk, network.  Troubleshooting 101 is to correlate measurements.  Looking at one datapoint, such as connections on the DB tells us nothing about what is happening on the machine actually responsible for creating connections.

**Comment by nitincchauhan** [comment] 2016-01-28 06:06
hibernate/sleeping/standby modes can be tricky to handle see: https://bugs.openjdk.java.net/browse/JDK-8074074

**Comment by victropolis** [comment] 2016-01-28 06:40
@brettwooldridge check this out.  Both of the following set of connections are actually from the SAME box.  the 10.100's are from the ethernet interface and the 10.101's are from the wifi interface.  Have you ever seen it where HikariCP establishes one set of connections per network interface?

<img width="365" alt="screen shot 2016-01-27 at 8 19 15 pm" src="https://cloud.githubusercontent.com/assets/359170/12637011/431f11ae-c54f-11e5-9869-9c389f667b9d.png">

<img width="369" alt="screen shot 2016-01-27 at 8 19 06 pm" src="https://cloud.githubusercontent.com/assets/359170/12637016/4934d524-c54f-11e5-89ca-95b431f30128.png">

**Comment by victropolis** [comment] 2016-01-28 06:47
@brettwooldridge just saw your post above.  thanks for the info.  Will see what I can glean tomorrow.  It IS a laptop (a MacBook Pro).  We never saw this issue with Proxool, the ancient and unsupported CP I'm replacing with HikariCP.  Many, if not most of our devs use laptops.  It cannot be that HikariCP doesn't play nice with laptops, can it?  I'm not sure how to proceed.  The fact that our dev postgres instance is regularly running out of connection slots is concerning some folks around here.  I will say that the containers that are running on our servers have not exhibited this behavior, so that is good.

**Comment by brettwooldridge** [comment] 2016-01-28 07:14
@victropolis HikariCP is completely unaware of the physical interfaces.  Which interface a request is routed out of is an OS-level decision based on the default routes.  How MacOS X is determining route priority I don't know.

In running through my theoretical scenario it is clear that the ``fillPool()`` method invoked by the housekeeper need not enqueue any more "add connection" tasks if there are already more than ``minimumIdle`` tasks awaiting execution (blocked for whatever reason).  This would prevent a spike that would occur after the (starvation | connectivity) condition ends.

Either way, even with the spike, I would expect a return to ``minimumIdle`` within 5 minutes if the pool is truly idle.

**Comment by victropolis** [comment] 2016-01-28 07:23
@brettwooldridge regarding the max connections of 100, I agree that it's high.  We had our min and max set to 5 and 100 respectively previously (with proxool).  I've maintained those configs for now.  I plan on running some load and performance testing with some lower numbers before going to production in 10 weeks.

**Comment by victropolis** [comment] 2016-01-28 07:26
@brettwooldridge the dba's blocked connections from those IPs tonight so that our builds and tests would stop failing due to insufficient connection slots.  Tomorrow I'll ask them to unblock them again and ask the dev to leave his container up all day and to run that command when I see the situation happening again.  Thanks!

**Comment by nitincchauhan** [comment] 2016-01-28 08:15
@victropolis pls do not forget to change log level to DEBUG

**Comment by victropolis** [comment] 2016-01-28 21:00
@brettwooldridge some findings.  I had him disable his wifi connection today and we still saw the ramp up in connections (no debug logging yet, that's next).  However, after he shutdown his container, postgres still thinks there are connections.

```
netstat -a | grep 10.100.132.169 | wc -l
695
```

Netstat returns 695 established connections on the db host.  But netstat returns 0 connections on the client.

I'll report what we find with the debug turned on.

**Comment by victropolis** [comment] 2016-01-28 22:30
@brettwooldridge struggling with getting the logging working since we use log4j.  Added dependency on slf4j-log4j12, but still not seeing it.  Still trying.

**Comment by brettwooldridge** [comment] 2016-01-28 23:41
You'll need to set com.zaxxer to DEBUG in the log4j config.

**Comment by brettwooldridge** [comment] 2016-01-28 23:44
That grep and wc will also list CLOSE_WAIT connections.  You only care about ESTABLISHED.

**Comment by victropolis** [comment] 2016-01-29 03:57
the were all ESTABLISHED.

**Comment by victropolis** [comment] 2016-01-29 04:55
@brettwooldridge OK, he left tomcat running on his laptop overnight again with DEBUG logging.

Currently, the database host shows 56 established connections from his ethernet interface:

```
netstat -a | grep 10.100.132.169 | grep ESTABLISHED | wc -l
56
```

And, 1150 established connections from his wifi interface:

```
netstat -a | grep 10.101.152.33 | grep ESTABLISHED | wc -l
1150
```

In the morning we'll check his logs and netstat and I'll report on what I find.

**Comment by brettwooldridge** [comment] 2016-01-29 08:03
@victropolis Any way to boot his connections from the server before leaving for the night?  Would be good to have a baseline.

Maybe stupid question, but I do have to ask, is there *any* other application running on the laptop that connects to the DB?  A SQL ui client, or console, etc.?

**Comment by victropolis** [comment] 2016-01-29 13:33
@brettwooldridge There were zero connections before he started tomcat and left for the night.  We should be in the office in a couple of hours.  I doubt that he has any other clients connected, but I'll ask him when I get in.  It would be quite a coincidence if it exhibited this pooling behavior, however.

BTW, right now he has 919 connections from his ethernet interface:

```
netstat -a | grep 10.100.132.169 | grep ESTABLISHED | wc -l
919
```

And, 257 from his wifi interface:

```
netstat -a | grep 10.101.152.33 | grep ESTABLISHED | wc -l
257
```

**Comment by brettwooldridge** [comment] 2016-01-29 13:54
I've published a snapshot, with out latest changes.  Though I have to say, if the pool is calling ``close()`` on connections as expected, and the OS stack (client-side) is showing no established connections, I'm at a bit of a loss.
```
<dependency>
  <groupId>com.zaxxer</groupId>
  <artifactId>HikariCP</artifactId>
  <version>2.4.4-SNAPSHOT</version>
</dependency>
```
Or direct download [here](https://oss.sonatype.org/service/local/repositories/snapshots/content/com/zaxxer/HikariCP/2.4.4-SNAPSHOT/HikariCP-2.4.4-20160129.134801-2.jar).

**Comment by brettwooldridge** [comment] 2016-01-29 14:40
@victropolis [PostgreSQL *Undead* queries](https://tech.zalando.com/blog/hack-to-terminate-tcp-conn-postgres/).  Similar symptoms:

> Recently we noticed that a few of our queries were running for hours or even days without terminating.
> ...
> We started to investigate and discovered that:
>
> * recipients of the data were non-existent;
> * ...
> * the underlying TCP connection was in the TCP ESTABLISHED state, but the client was already gone,
>   so no data was being transmitted over it.

**Comment by victropolis** [comment] 2016-01-29 15:33
@brettwooldridge attached please find the logs I collected.

[member_manager_hikari.txt](https://github.com/brettwooldridge/HikariCP/files/109952/member_manager_hikari.txt)
[member_service_hikari.txt](https://github.com/brettwooldridge/HikariCP/files/109951/member_service_hikari.txt)

**Comment by brettwooldridge** [comment] 2016-01-29 16:04
@victropolis Wow, that is some crazy sh*t.  This...
```
2016-01-29 00:06:54,804 WARN  [e04...] [Hikari housekeeper (pool 1-MemberConnectionPool)] [pool.HikariPool] - 1-MemberConnectionPool - Unusual system clock change detected, soft-evicting connections from pool.
...
2016-01-29 00:06:54,809 DEBUG [e04...] [Hikari housekeeper (pool 1-MemberConnectionPool)] [pool.HikariPool] - Before cleanup	pool 1-MemberConnectionPool stats (total=0, active=0, idle=0, waiting=0)
2016-01-29 00:06:54,809 DEBUG [e04...] [Hikari housekeeper (pool 1-MemberConnectionPool)] [pool.HikariPool] - After cleanup	pool 1-MemberConnectionPool stats (total=0, active=0, idle=0, waiting=0)
2016-01-29 00:06:54,809 DEBUG [e04...] [Hikari housekeeper (pool 1-MemberConnectionPool)] [pool.HikariPool] - Before cleanup	pool 1-MemberConnectionPool stats (total=0, active=0, idle=0, waiting=0)
2016-01-29 00:06:54,809 DEBUG [e04...] [Hikari housekeeper (pool 1-MemberConnectionPool)] [pool.HikariPool] - After cleanup	pool 1-MemberConnectionPool stats (total=0, active=0, idle=0, waiting=0)
2016-01-29 00:06:54,809 DEBUG [e04...] [Hikari housekeeper (pool 1-MemberConnectionPool)] [pool.HikariPool] - Before cleanup	pool 1-MemberConnectionPool stats (total=0, active=0, idle=0, waiting=0)
2016-01-29 00:06:54,809 DEBUG [e04...] [Hikari housekeeper (pool 1-MemberConnectionPool)] [pool.HikariPool] - After cleanup	pool 1-MemberConnectionPool stats (total=0, active=0, idle=0, waiting=0)
2016-01-29 00:06:54,809 DEBUG [e04...] [Hikari housekeeper (pool 1-MemberConnectionPool)] [pool.HikariPool] - Before cleanup	pool 1-MemberConnectionPool stats (total=0, active=0, idle=0, waiting=0)
```
The housekeeper runs at a "fixed interval" of [30 seconds](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L133).  For each run, a "Before" and "After" message are logged.  Yet, the Java ScheduledExecutor is running the task 100+ times "in the same millisecond".

This is right after unusual clock motion is detected.  It appears that time is "frozen" or some other abherent condition that is causing the executor to think it is time to fire again...

**Comment by victropolis** [comment] 2016-01-29 16:30
@brettwooldridge must be related to what @nitincchauhan posted above: https://bugs.openjdk.java.net/browse/JDK-8074074

**Comment by victropolis** [comment] 2016-01-29 17:05
@brettwooldridge check this out: http://stackoverflow.com/a/5568375

**Comment by brettwooldridge** [comment] 2016-01-30 01:18
@victropolis That is the case for ``Timer``.  HikariCP *does* use the ``ScheduledExecutorService`` as recommended by that post ... which *shouldn't* exhibit "catch-up" behavior.

**Comment by billoneil** [comment] 2016-01-30 01:50
Could it be related to this?

https://github.com/brettwooldridge/HikariCP/blob/bd7e3ba6db56edba7ca29ed374d91f1996588ece/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L133

scheduleAtFixedRate - If any execution of this task takes longer than its
period, then subsequent executions may start late, but will not
concurrently execute.

scheduleWithFixedDelay - Creates and executes a periodic action that
becomes enabled first after the given initial delay, and subsequently with
the given delay between the termination of one execution and the
commencement of the next.

Sounds like scheduleAtFixedRate ensures the tasks will not execute
concurrently but they could still queue up. scheduleWithFixedDelay will not
queue the next task until after the completion + delay of the previous
execution.

**Comment by nitincchauhan** [comment] 2016-01-30 05:48
@brettwooldridge IMO this behavior is 'also' because of fixed size of closing queue. this keeps housekeeper busy closing many connections in 'housekeeper' thread instead of 'connection closer' that it prompts an other 'clock changed'.
I already committed this fixed to proportionate size in PR https://github.com/brettwooldridge/HikariCP/pull/539

**Comment by nitincchauhan** [comment] 2016-01-30 11:33
its confusing but it looks like the condition should be:
`if (now < clockSource.plusMillis(previous, HOUSEKEEPING_PERIOD_MS)
 || now > clockSource.plusMillis(previous, (2 * HOUSEKEEPING_PERIOD_MS))) {`

**Comment by brettwooldridge** [comment] 2016-01-30 14:12
@victropolis Published an updated snapshot.

<dependency>
  <groupId>com.zaxxer</groupId>
  <artifactId>HikariCP</artifactId>
  <version>2.4.4-SNAPSHOT</version>
</dependency>

Direct download [here](https://oss.sonatype.org/service/local/repositories/snapshots/content/com/zaxxer/HikariCP/2.4.4-SNAPSHOT/HikariCP-2.4.4-20160130.141029-3.jar).

**Comment by victropolis** [comment] 2016-01-30 15:40
@brettwooldridge thanks Brett.  Will test on Monday when we're back in the office.  Enjoy the rest of your weekend.

**Comment by victropolis** [comment] 2016-01-30 15:40
@brettwooldridge when will 2.4.4 be released?

**Comment by brettwooldridge** [comment] 2016-01-31 01:35
@victropolis I'd like to put out a release candidate on Monday (Tokyo time) and release one week later if all goes well.

**Comment by victropolis** [comment] 2016-02-02 16:39
@brettwooldridge FYI, we're finally testing today and overnight tonight.  been getting pounded with snow.  looks good so far.

**Comment by victropolis** [comment] 2016-02-03 04:43
@brettwooldridge everything is still looking great through the night.  database connections remain stable at or near the minimumIdle setting.  I'll post the logs in the morning, if there's anything interesting in there.  Thanks again for re-opening this issue @brettwooldridge and thanks for resolving it.  I'll be waiting for 2.4.4 to be released.

**Comment by victropolis** [comment] 2016-02-03 04:57
BTW, I no longer see connections for wifi and ethernet adapter.  only the ethernet adapter.

**Comment by brettwooldridge** [comment] 2016-02-03 14:59
@victropolis HikariCP 2.4.4 RC1 [is available](https://groups.google.com/forum/#!topic/hikari-cp/Hp9D-Q8IVtg) for testing.

**Closed** 2016-02-13 05:03 UTC
Labels: question
