### ISSUE TITLE
Not able to override Transaction Isolation level at DataSource level

### ISSUE THREAD

**Issue by shashikant-lokare** [brettwooldridge/HikariCP#2111] opened 2023-09-17 06:52 UTC
I have created the DataSource by using below code. After I run the queries, connection is still taking data source as read committed only.

```
@Primary
    @Bean(name="labSoDataSource")
    public DataSource labSoDataSource() throws SQLException {
        HikariDataSource dataSource = new HikariDataSource();
        dataSource.setPoolName("LabSoDataSource");
        dataSource.setJdbcUrl(labSoDataSourceConfig.getUrl());
        dataSource.setUsername(labSoDataSourceConfig.getUsername());
        dataSource.setPassword(labSoDataSourceConfig.getPassword());
        dataSource.setDriverClassName(labSoDataSourceConfig.getDriverClassName());
        dataSource.setMaximumPoolSize(labSoDataSourceConfig.getMaximumPoolSize());
        dataSource.setConnectionTimeout(labSoDataSourceConfig.getConnectionTimeout());
        dataSource.setTransactionIsolation("TRANSACTION_READ_UNCOMMITTED");
        dataSource.setMaxLifetime(60000);
        return dataSource;
    }
```

I have used the set property

Method description says

`Set the default transaction isolation level. The specified value is the constant name from the Connection class, eg. TRANSACTION_REPEATABLE_READ.`

Am I setting the property wrongfully or is it a bug. Please help here.

Thanks in advance.

**Comment by lfbayer** [comment] 2023-09-20 12:48
I don't see anything obviously wrong in your code, but I also think it is most likely not a bug in HikariCP. There are junit tests that cover this exact behavior.

I would recommend that you investigate further on your side as there isn't enough information here for me to be able to diagnose why it isn't working for you.

If you are able to narrow it down to being a HikariCP bug, then it would be helpful if you could create a pull request with a junit test that reproduces the issue.

For now I'm closing this ticket as not a bug.

**Closed as completed by lfbayer** 2023-09-20 12:48 UTC
Labels: not-a-bug
