### ISSUE TITLE
lock wait when executing same query SQL

### ISSUE THREAD

**Issue by rogue2yjg** [brettwooldridge/HikariCP#1102] opened 2018-02-28 05:48 UTC
#### Environment
```
HikariCP version: java7-2.4.13
JDK version     : 1.7.0_79
Database        : PostgreSQL 9.4.1
Driver version  : 42.1.4.jre7
```
-----------------------------------------------------------------------------------------
@brettwooldridge

Hi brett,
I want to consult with you about the previous "cancelling statement due to user request" problem.

As vlsi said, I had increased the defaultStatementOut value in mybatis config file and there hadn't been problems any more. But I thought that wasn't a grassroots solution.

On the one hand, I would try to improve performance of the query sql.
On the other hand, I found an interesting phenomenon in my test case. I used a thread pool with 5 threads to run 5 query sql tasks, and you could find the HikariCP config in application.properties in my test case. Every query sql task was same and it would cost more than 2 seconds. When I started the test, the sql execution log and the HikariCP adding connection log appeared successively. But the program came to block after the log appeared 5 times, and after about 13 seconds, the 5 query results log appeared almost at the same time.

What I doubted were below:
1、The sql was just a query and there shouldn't be any lock wait when the 5 sql commands were executed in pg server concurrently;
2、The 5 tasks used 5 different db connections to run the query sql, right?

[smart-fire.zip](https://github.com/brettwooldridge/HikariCP/files/1765731/smart-fire.zip)

**Comment by brettwooldridge** [comment] 2018-02-28 13:39
This part of the pom is trying to pull dependencies from some repository called "eric-repo" with a *local* IP address of 192.168.0.241.  I don't know what that is, but it is blocking building this project:
```
<parent>
    <groupId>com.yundun119</groupId>
    <artifactId>smart-fire</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
```
Please fix the ``pom.xml``. Additionally, please provide instructions how to run the test.  I know nothing about Spring or Spring-boot, and I do not have the time to mess around with a project .zip that comes with no instructions.

**Comment by rogue2yjg** [comment] 2018-03-01 00:06
@brett,

Ok, I will refactor my project without Spring, Maven and Mybatis.

**Comment by brettwooldridge** [comment] 2018-05-19 10:12
I tried your project and could not reproduce it.  However, there was a lot missing, including implementations of DAO classes.  I also had to reverse-engineer your SQL schema.  This issue is old enough that I assume that you solved the issue yourself, so I am closing this.

**Closed by brettwooldridge** 2018-05-19 10:12 UTC
