### ISSUE TITLE
error releasing connection

### ISSUE THREAD

**Issue by jefimm** [brettwooldridge/HikariCP#456] opened 2015-10-11 09:32 UTC
When connection does not have initial catalog (for example it is wrapped in subclass  of org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource)  the release connection should not attempt to set catalog e.g. 

PoolBase:resetConnectionState

      if ((dirtyBits & DIRTY_BIT_CATALOG) != 0) {
         final String currentCatalog = proxyConnection.getCatalogState();
         if ((currentCatalog != null && !currentCatalog.equals(catalog)) || (currentCatalog == null && catalog != null)) {
            connection.setCatalog(catalog);
            resetBits |= DIRTY_BIT_CATALOG;
         }
      }

should be 

      if ((dirtyBits & DIRTY_BIT_CATALOG) != 0 && catalog != null) {
         final String currentCatalog = proxyConnection.getCatalogState();
         if ((currentCatalog != null && !currentCatalog.equals(catalog)) || (currentCatalog == null)) {
            connection.setCatalog(catalog);
            resetBits |= DIRTY_BIT_CATALOG;
         }
      }

**Comment by nitincchauhan** [comment] 2015-10-12 09:15
@jefimm 
What is the error / exception from stack trace ?
The code looks correct and is to reset connection catalog to its initial value even if it is null.

**Comment by jefimm** [comment] 2015-10-12 09:20
At least with Spring/Hibernate + MySQL we got:
org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: S1009
org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Catalog can not be null

**Comment by nitincchauhan** [comment] 2015-10-12 09:33
duplicate of https://github.com/brettwooldridge/HikariCP/issues/410
@jefimm see if solution there helps !

**Comment by jefimm** [comment] 2015-10-12 09:57
This is a slightly different issue and for multi-tenant apps where each tenant uses separate catalog there might be  no default catalog on connection and setting catalog to null should be avoided, as it was in 2.3.7

**Comment by nitincchauhan** [comment] 2015-10-12 10:21
@jefimm one request:
do not set catalog in pool configuration (as in your case)
call connection.**get**Catalog() immediately after borrowing connection from pool and check if it returns null or non-null

**Comment by jefimm** [comment] 2015-10-12 10:50
returned empty string

**Comment by nitincchauhan** [comment] 2015-10-12 15:29
@jefimm Thanks
Included change required for this report in my pull request.

**Closed** 2015-10-14 13:59 UTC
