### ISSUE TITLE
Broken Video on "About Pool Sizing" wiki page

### ISSUE THREAD

**Issue by mgyucht** [brettwooldridge/HikariCP#1566] opened 2020-04-06 10:20 UTC
The video on the About Pool Sizing wiki page is broken. Here's a YT link to the same video (I assume) that works: https://www.youtube.com/watch?v=xNDnVOCdvQ0

**Comment by dasl-** [comment] 2020-04-13 20:44
diff to fix it: https://gist.github.com/d9ff706280eb11e79ac12d985a949185

**Comment by lfbayer** [comment] 2020-05-13 07:58
Duplicate of #1539

Link is fixed.

**Closed as completed by lfbayer** 2020-05-13 07:58 UTC
