### ISSUE TITLE
Apparent connection leak detected

### ISSUE THREAD

**Issue by aalbacha** [brettwooldridge/HikariCP#1106] opened 2018-03-06 23:49 UTC
#### Environment
```
HikariCP version: 2.4.7
JDK version     : 1.8.0_121-b13
Database        : Oracle 11.2.0.3
Driver version  : jdbc:oracle:thin
Server OS: SunOS 5.11
JOOQ Version: 3.10.4
Web Server: Apache Tomcat/9.0.1

#### Configuration

2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - kwecm - idleTimeout is close to or more than maxLifetime, disabling it.
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - kwecm - configuration:
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - autoCommit......................true
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - catalog.........................null
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - connectionInitSql...............null
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - connectionTestQuery............."SELECT 1 FROM DUAL"
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - dataSource......................null
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - dataSourceClassName.............null
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................null
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>}
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - driverClassName................."oracle.jdbc.driver.OracleDriver"
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............null
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - idleTimeout.....................0
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - jdbcUrl........................."jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = dbsrv-cluster)(PORT = 1521))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = MOTPROD1)))"
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........15000
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - maxLifetime.....................50000
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - maximumPoolSize.................200
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - metricRegistry..................null
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........null
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - minimumIdle.....................5
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - password........................<masked>
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - poolName........................"kwecm"
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - readOnly........................false
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - registerMbeans..................false
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - scheduledExecutorService........null
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - threadFactory...................null
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - transactionIsolation............null
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - username........................"KWECM"
DEBUG 2018-02-20 18:03:46 com.zaxxer.hikari.HikariConfig - validationTimeout...............5000



we have two nodes of our application connect to RAC oracle DB, and we are using Hikari in our application to connect to DB and every thing working smoothly, after some times 1 weeks the application hanged and we get the following error:

WARN  2018-02-21 18:29:43 c.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for oracle.jdbc.driver.T4CConnection@7babe4c1, stack trace follows
java.lang.Exception: Apparent connection leak detected

Caused by: java.sql.SQLTransientConnectionException: kwecm - Connection is not available, request timed out after 30000ms.

we have tried to configured maxlifetime, connectionleak detection but no chance.

in attach you can find the full log of one node:

[35.txt](https://github.com/brettwooldridge/HikariCP/files/1787161/35.txt)

Thanks.


-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment] 2018-03-07 07:40
@aalbacha First, please upgrade to the latest version of HikariCP; either v2.4.13 or v2.7.8.  In HikariCP v2.4.8, one release after yours, additional logging was added to report when a previously reported leaked connection is actually returned to the pool.  Given that you are on Java 8, I strongly recommend that you upgrade to v2.7.8.

Several race conditions have been fixed after v2.4.7, and I suspect that your leak could be caused by one of them; but there is no way to know until after you have upgraded your driver.

Lastly, why is ``maxLifetime`` so short, and yet ``idleTimeout`` is 0?  This is going to do nothing more than cause additionally connection thrashing.

**Comment by aalbacha** [comment] 2018-03-14 10:17
@brettwooldridge Thanks for your replying, We have upgraded to v2.7.8 and and increase the idleTimeout and maxLifetime as you can see in following configuration printed from our log and we got the same case of aparent leak detection 

DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - kwecm - configuration:
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - autoCommit......................true
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - catalog.........................none
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - connectionInitSql...............none
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - connectionTestQuery............."SELECT 1 FROM DUAL"
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - dataSource......................none
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - dataSourceClassName.............none
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................none
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>}
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - driverClassName................."oracle.jdbc.driver.OracleDriver"
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............none
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - idleTimeout.....................240000
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - initializationFailTimeout.......1
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - jdbcUrl.........................jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = dbsrv-cluster)(PORT = 1521))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = MOTPROD1)))
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........15000
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - maxLifetime.....................300000
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - maximumPoolSize.................200
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - metricRegistry..................none
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........none
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - minimumIdle.....................5
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - password........................<masked>
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - poolName........................"kwecm"
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - readOnly........................false
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - registerMbeans..................false
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - scheduledExecutor...............none
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - scheduledExecutorService........internal
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - schema..........................none
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - threadFactory...................internal
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - transactionIsolation............default
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - username........................"KWECM"
DEBUG 2018-03-14 01:16:46 com.zaxxer.hikari.HikariConfig - validationTimeout...............5000

attached is the log

[catalina36.zip](https://github.com/brettwooldridge/HikariCP/files/1810530/catalina36.zip)

Thanks

**Comment by brettwooldridge** [comment] 2018-03-14 17:30
@aalbacha Wow.  You've got a witch's brew of JDBC components in there: TransactionTemplate, DataSourceTransactionManager, Jooq.  And it looks like you are mixing them in combination with annotations.

You're going to have to ask this question over on the Spring forum.  I can unequivocally say that when HikariCP reports a leak, if there is no corresponding "unleak" log, then the application or framework *is leaking* connections.

After grepping the log, I find that only three connections were returned after being reported as leaked, which means the rest were true leaks:
```
WARN  2018-03-14 09:44:07 c.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for oracle.jdbc.driver.T4CConnection@65a4c312 on thread http-nio-8080-exec-19, stack trace follows
WARN  2018-03-14 09:44:11 c.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for oracle.jdbc.driver.T4CConnection@3edab694 on thread http-nio-8080-exec-46, stack trace follows
WARN  2018-03-14 09:45:06 c.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for oracle.jdbc.driver.T4CConnection@6b63200e on thread http-nio-8080-exec-11, stack trace follows
INFO  2018-03-14 09:45:29 c.zaxxer.hikari.pool.ProxyLeakTask - Previously reported leaked connection oracle.jdbc.driver.T4CConnection@6b63200e on thread http-nio-8080-exec-11 was returned to the pool (unleaked)
INFO  2018-03-14 09:45:30 c.zaxxer.hikari.pool.ProxyLeakTask - Previously reported leaked connection oracle.jdbc.driver.T4CConnection@3edab694 on thread http-nio-8080-exec-46 was returned to the pool (unleaked)
INFO  2018-03-14 09:45:30 c.zaxxer.hikari.pool.ProxyLeakTask - Previously reported leaked connection oracle.jdbc.driver.T4CConnection@65a4c312 on thread http-nio-8080-exec-19 was returned to the pool (unleaked)
```

The question is, ultimately, what component is responsible for acquiring and releasing connections from the pool?

Every leak reported in the log starts with the same stacktrace:
```
WARN  2018-03-14 09:25:14 c.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for oracle.jdbc.driver.T4CConnection@1550f948 on thread http-nio-8080-exec-11, stack trace follows
java.lang.Exception: Apparent connection leak detected
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:204)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
```
So clearly ``TransactionTemplate`` and (more likely) ``DataSourceTransactionManager`` are involved in the problem.  What comes *next* in the stack varies...
```
at com.knowledgeways.ecm.cts.correspondence.Correspondences$Transactional.linkable(Correspondences.java:266)
```
```
at com.knowledgeways.ecm.cts.correspondence.AttAclCorrespondence.publish(AttAclCorrespondence.java:83)
```
```
at com.knowledgeways.ecm.cts.correspondence.internal.outgoing.InternalOutgoing$Transactional.view(InternalOutgoing.java:78)
```
etc.

Anyway, this is not a HikariCP bug, so I am closing it.  Feel free to reference this issue when discussing in the Spring forum.

**Closed by brettwooldridge** 2018-03-14 17:30 UTC
Labels: more-information-needed, question
