### ISSUE TITLE
NullPointerException in jdbc

### ISSUE THREAD

**Issue by sytolk** [brettwooldridge/HikariCP#246] opened 2015-01-28 20:21 UTC
Hi,
HikariCP works but sometimes (maybe if its have no queries to DB for a long time) I have this NullPointerException and have no idea why?

```
Exception in thread "HikariCP utility thread (pool springHikariCP)" Exception in thread "HikariCP utility thread (pool springHikariCP)" java.lang.NullPointerException
	at com.mysql.jdbc.MysqlIO.setSocketTimeout(MysqlIO.java:5316)
	at com.mysql.jdbc.ConnectionImpl$12.run(ConnectionImpl.java:6102)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at com.mysql.jdbc.MysqlIO.setSocketTimeout(MysqlIO.java:5316)
	at com.mysql.jdbc.ConnectionImpl$12.run(ConnectionImpl.java:6102)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

this is my spring configuration for MySql
```
<bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
        <property name="poolName" value="springHikariCP"/>
        <property name="connectionTestQuery" value="SELECT 1"/>
        <property name="dataSourceClassName" value="com.mysql.jdbc.jdbc2.optional.MysqlDataSource"/>
        <property name="maximumPoolSize" value="${jdbc.maxConnectionsPerPartition}"/>
        <property name="connectionInitSql" value="SET time_zone='${database.timezone}'"/>

        <property name="dataSourceProperties">
            <props>
                <prop key="url">${jdbc.url}</prop>
                <prop key="user">${jdbc.user}</prop>
                <prop key="password">${jdbc.pass}</prop>
                <prop key="cachePrepStmts">true</prop>
                <prop key="prepStmtCacheSize">250</prop>
                <prop key="prepStmtCacheSqlLimit">2048</prop>
                <prop key="useServerPrepStmts">true</prop>
            </props>
        </property>
    </bean>
```

**Comment by brettwooldridge** [comment] 2015-01-28 22:59
This should be fixed in 2.3.1.  It is actually a MySQL issue, http://bugs.mysql.com/bug.php?id=75615, that we tripped over in 2.3.0 and worked-around in 2.3.1.  What version are you running?

**Comment by sytolk** [comment] 2015-01-29 07:51
yes I have use 2.3.0 version with Java 8 
```
<dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>2.3.0</version>
            <scope>compile</scope>
        </dependency>
```
maybe version 2.3.1 is not updated in maven central yet.
http://mvnrepository.com/artifact/com.zaxxer/HikariCP

But I will try snapshot. Thanks!

**Comment by brettwooldridge** [comment] 2015-01-29 09:46
Try this search: http://search.maven.org/#search%7Cga%7C1%7Chikaricp

**Comment by brettwooldridge** [comment] 2015-01-29 12:02
Duplicate of #236

**Closed by brettwooldridge** 2015-01-29 12:02 UTC
Labels: duplicate
