### ISSUE TITLE
Materialised view are not discovered

### ISSUE THREAD

**Issue by mozinrat** [brettwooldridge/HikariCP#466] opened 2015-10-20 00:03 UTC
Using Hikari CP the code runs but when we hit an api which is using postgres-9.4 materialized view it says relation does not exists.

**Comment by brettwooldridge** [comment] 2015-10-20 02:20
@mozinrat Can you provide a stacktrace?  HikariCP does nothing to the executed SQL except pass it through to the underlying driver, so it is difficult to imagine how HikariCP could be affecting this.  Are you sure that the database user has visibility (permission) on the view in question?

**Comment by vlsi** [comment] 2015-10-20 13:21
@mozinrat , which version of jdbc driver are you using?
You might happen to run into https://github.com/pgjdbc/pgjdbc/pull/403 (that is not yet released in pgjdbc)

**Comment by mozinrat** [comment] 2015-10-20 15:40
@vlsi we are using org.postgresql:postgresql:9.4-1201-jdbc41, combined with  config.setDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");

**Comment by vlsi** [comment] 2015-10-20 15:44
@mozinrat , can you try building pgjdbc from master branch?
I think it should solve the problem for you.

**Comment by mozinrat** [comment] 2015-10-20 15:47
@vlsi which one should i use (JDBC4/JDBC41/JDBC42)
JDK 1.6 - JDBC4. Support for JDBC4 methods is not complete, but the majority of methods are implemented.
JDK 1.7 - JDBC41. Support for JDBC4 methods is not complete, but the majority of methods are implemented.
JDK 1.8 - JDBC42. Support for JDBC4 methods is not complete, but the majority of methods are implemented

**Comment by vlsi** [comment] 2015-10-20 15:49
I mean
```
git clone https://github.com/pgjdbc/pgjdbc.git
ant
```
Then pick a jar from `jars` subfolder

**Comment by mozinrat** [comment] 2015-10-20 18:03
@vlsi tried the jar (it builds 9.4-1204-jdbc42 by default) as well as other maven published jars (1204-jdbc4, 1204-jdbc42, 1204-jdbc41) and everyone gives same error. The error only resolves If i not use HikariCP and let spring take care of connections

**Comment by mozinrat** [comment] 2015-10-20 18:06
@brettwooldridge I have put the log file at https://drive.google.com/file/d/0BzUr4xkBBynBTThtV3B5NXZydXc/view?usp=sharing

**Comment by vlsi** [comment] 2015-10-20 18:19
```Hibernate: select code,text,city_code,id_place from airportSuggest WHERE phrase @@ to_tsquery( ? 
)
ERROR: relation "airportsuggest" does not exist
```

@mozinrat , What is the name of the table? Which value do you use in `@Table(name=`? It looks like the table/mview has name in mixed case and miss to quote it (see here: http://stackoverflow.com/a/3611916/1261287)

**Comment by mozinrat** [comment] 2015-10-20 18:24
airportSuggest is the materialized view, there are no entities as @Table for this, as we are using nativeSqlQuery. While parsing we read an object array and use it to extract values.

**Comment by vlsi** [comment] 2015-10-20 18:26
Do you have quotes in that nativeSqlQuery?

**Comment by mozinrat** [comment] 2015-10-20 18:28
We used spring-data-jpa as below 
@Query(value = "select code,text,city_code,id_place from airportSuggest WHERE phrase @@ to_tsquery( ?1 )", nativeQuery = true)
    List<Object[]> findByCodeOrName(String phase);

**Comment by vlsi** [comment] 2015-10-20 18:29
Put quotes around airportSuggest or do not use tables with mixed-case names.

**Comment by mozinrat** [comment] 2015-10-20 18:38
refactored view as airportsuggest and used the same 
@Query(value = "select code,text,city_code,id_place from airportsuggest WHERE phrase @@ to_tsquery( ?1 )", nativeQuery = true)
List findByCodeOrName(String phase);
The issue prevails

**Comment by vlsi** [comment] 2015-10-20 18:41
Could you please be polite and provide the exact stacktrace/log/whatever?
No one wants looking into "The issue prevails"

**Comment by mozinrat** [comment] 2015-10-20 20:04
Please excuse me, I am not a native english speaker so not aware of it.I am sorry for it.
 When I made the above changes and avoided camel case, I got exact same error what I had in the attached log. Its just the logs shows the same entity in small case  as 
Caused by: org.postgresql.util.PSQLException: ERROR: relation "airportsuggest" does not exist
  Position: 42
    org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)

**Comment by vlsi** [comment] 2015-10-20 20:20
>I am not a native english speaker so not aware of it.

I do not mean the wording is bad. I mean if you report a bug you should provide "test case", "expected result", "actual result".
Otherwise it would be hard to impossible to analyze.

"issue prevails" is bad.
"here is the log, stacktrace, and the code to reproduce it" is good.

> I got exact same error what I had in the attached log.

Can you reattach the log once again?
I suspect the change was not applied.

You might happen to connect to the wrong database.
You might happen to put the mview into some schema.
Did you try running exactly the same SQL via PreparedStatement?

**Comment by mozinrat** [comment] 2015-10-20 20:33
@vlsi https://drive.google.com/file/d/0BzUr4xkBBynBM2s5eG1GbG0zZmM/view?usp=sharing is the new log. I used the same JPA query in native sql form with small case only (airportsuggest).
The other thing is as I mentioned earlier, when I remove HikariCP and add the spring datasource, it works for me. I can now think that the database connection may have some issue
The original datasource config is as 

        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName(environment.getProperty("spring.datasource.driverClassName"));
        dataSource.setUrl(environment.getProperty("spring.datasource.url"));
        dataSource.setUsername(environment.getProperty("spring.datasource.username"));
        dataSource.setPassword(environment.getProperty("spring.datasource.password"));
        return dataSource;

Some how I think its not related to tables but access or something else 
Here is hikari config 

        log.debug("Configuring Datasource");
        if (environment.getProperty("spring.datasource.url") == null && environment.getProperty("spring.datasource.username") == null) {
            log.error("Your database connection pool configuration is incorrect! The application" +
                            " cannot start. Please check your Spring profile, current profiles are: {}",
                    Arrays.toString(environment.getActiveProfiles()));
            throw new ApplicationContextException("Database connection pool is not configured correctly");
        }
        HikariConfig config = new HikariConfig();
        log.info("Connecting to database "+environment.getProperty("spring.datasource.url")+ " with username "  + environment.getProperty("spring.datasource.username") + "/"+environment.getProperty("spring.datasource.password"));

        config.setDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");
        config.setJdbcUrl(environment.getProperty("spring.datasource.url"));
        config.setUsername(environment.getProperty("spring.datasource.username"));
        config.setPassword(environment.getProperty("spring.datasource.password"));
        return new HikariDataSource(config);
//
The connection log above prints
Connecting to database jdbc:postgresql://localhost:5432/iatadata with username postgres/root --which are correct database and credentials
Am I missing something.

**Comment by vlsi** [comment] 2015-10-20 20:40
Can you try executing `select current_schemas(true)` via both datasources? What will it return?
Could it be some kind of "default schema" being set when using spring DS?

**Comment by mozinrat** [comment] 2015-10-20 22:21
I fixed it I have to change from     config.setDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");
to  config.setDriverClassName(environment.getProperty("spring.datasource.driverClassName")); and it works

**Closed** 2015-10-20 22:31 UTC
Labels: more-information-needed, question
