### ISSUE TITLE
Toomany Connections : 121 connections created while maximumPoolSize=10?

### ISSUE THREAD

**Issue by namjitharavind** [brettwooldridge/HikariCP#1568] opened 2020-04-12 08:30 UTC
121 connections created while config as below

spring.datasource.hikari.pool-name=DTE HikariConnectionPool
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.minimumIdle=8
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifeTime=1800000
spring.datasource.hikari.autoCommit=true
spring.datasource.validationQuery=SELECT 1
spring.datasource.hikari.leakDetectionThreshold=10000

Please help?

Getting too many connections error while connecting.

**Comment by johnou** [comment] 2020-04-12 09:04
Please provide debug logs for the hikari package. Are you sure all connections originate from your application? How many pool instances?

**Comment by namjitharavind** [comment] 2020-04-12 09:26
Now out of 130 from application only 18 but localhost root user connection count is  96.  root user from outside is 8. Any idea about how came localhost root user count is 96?

below is th log.

 by: com.zaxxer.hikari.pool.PoolBase$ConnectionSetupException: java.sql.SQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"

![image](https://user-images.githubusercontent.com/4006905/79065669-ca294c00-7ccf-11ea-8825-88953ec2cb05.png)

**Comment by namjitharavind** [comment] 2020-04-12 09:57
I had configured wait_timeout=2400000 in /etc/mysql/mysql.conf.d/mysqld.cnf. Now commented out that(no its defualt value 28800). Its working fine for now. If anything coming wrong later i will comment. From hikari side there was no issue i think. This is because of wrong mysql configuration.

**Comment by namjitharavind** [comment] 2020-04-12 11:25
No its still growing.

**Comment by namjitharavind** [comment] 2020-04-12 12:16
This following is the next try. Update max_user_connections for root user from local. 
SELECT max_user_connections FROM mysql.user WHERE user='root' AND host='localhost';
UPDATE mysql.user SET max_user_connections = 2
WHERE user='root' AND host='localhost';
FLUSH PRIVILEGES;

After restart it's not growing more than two connections for root user from the localhost. Thinks it working.

**Comment by eischet** [comment] 2020-04-29 09:04
I just got a report on my app using HikariCP 3.4.2 with Oracle that it's using hundreds of Oracle connections instead of the 10 configured connections. We compared the PIDs between DB and Web server, and they matched the single process running on their server. 
My database code was unchanged in my latest update (really), but I had upgraded HikariCP from 3.4.1. I'll try downgrading the dependency now, maybe something happened between 3.4.1 and 3.4.2?

**Comment by brettwooldridge** [comment] 2020-04-30 16:22
@eischet Very strange.  What does ``netstat -an`` show on the application machine and the db server in terms of connections?  I recommend enabling debug logging.  HikariCP logs every physical connection close (and acquisition).

Assuming a complete log, you should be able to:

``grep "Added connection" your.log | wc -l``

and 

``grep "Closing connection" your.log | wc -l``

and the difference between those two numbers should not be greater than ``maximumPoolSize``.

**Comment by eischet** [comment] 2020-04-30 16:29
Thanks, I‘ll stage a test ASAP. I can’t directly access the customer‘s machine, so I have to believe when they say that over 700 connections were initiated, with max size set to 10. We’re down to the previous version now, since yesterday, and the issue hasn’t appeared again (yet).

**Comment by eischet** [comment] 2020-05-04 09:22
In my case, it's not HikariCP's fault but my own. My app is able to reconfigure data sources at runtime, and these are configured by the user/admin. Shutting down a data source fails to close all connections, and that's something I need to fix in my own code. Thanks for the debugging hints, Brett!

**Comment by brettwooldridge** [comment] 2020-05-05 04:12
@eischet Whew! Glad you found the cause.

**Comment by brettwooldridge** [comment] 2020-05-05 04:14
@namjitharavind Any update?  Any chance your code is also recreating the datasource without evicting connections and shutting down the datasource?

**Comment by namjitharavind** [comment] 2020-05-08 05:21
@brettwooldridge After my above **root** user **max_user_connections=2** database update. It's only growing up to the pool size. It's working fine now. I have created another user for the application instead of the user root.

**Closed as completed** 2020-05-08 05:21 UTC
