### ISSUE TITLE
FastList is not thread-safe

### ISSUE THREAD

**Issue by mtambara** [brettwooldridge/HikariCP#591] opened 2016-03-03 20:03 UTC
Hi @brettwooldridge,

This issue is to notify you about a concurrency bug. When multiple threads create and close `PreparedStatements`, `ProxyStatement.close()` calls `ProxyConnection.untrackStatement(Statement)` multiple times with different statements. `ProxyConnection` then attempts to remove these from `openStatements`. The problem is that `FastList` is not thread-safe, so these concurrent removes end up throwing an `ArrayIndexOutOfBoundsException`. I've created `ConcurrentCloseConnectionTest` to demonstrate this problem (see #590).

As we said in #451, we're getting closer to our 7.0 release. We have a workaround so our CI tests pass, but we'd like to have a real solution in place with enough time to allow for rigorous testing. Please let me know if you have any questions or need more input.

Thanks!
Matt

cc @shuyangzhou

**Comment by nitincchauhan** [comment] 2016-03-04 06:16
IMHO, the test case given in 590 is not valid. JDBC api is thread safe as long as you are NOT SHARING connection / statement with multiple threads.

You should refactor as::

`
ExecutorService` executorService = Executors.newFixedThreadPool(10);
List<Future> futures = new ArrayList<>();
try (HikariDataSource ds = new HikariDataSource(config) {
   futures.add(executorService.submit(new Callable<Void>() {
      public Void call() throws Exception {
         try (Connection connection = ds.getConnection()) {
            try (PreparedStatement preparedStatement = connection.prepareStatement("")) {
               preparedStatement.execute(...)
            }
         }
         return null;
      }
   }
}
`
or use add/ExecuteBatch() appropriately for performance.

**Comment by nitincchauhan** [comment] 2016-03-04 06:24
IMHO, the test case given in 590 is not valid. JDBC api is thread safe as long as you are NOT SHARING connection / statement with multiple threads.

You should refactor as::

    ExecutorService` executorService = Executors.newFixedThreadPool(10);
    List<Future> futures = new ArrayList<>();
    try (HikariDataSource ds = new HikariDataSource(config) {
       futures.add(executorService.submit(new Callable<Void>() {
          public Void call() throws Exception {
             try (Connection connection = ds.getConnection()) {
                try (PreparedStatement preparedStatement = connection.prepareStatement("")) {
                   preparedStatement.execute(...)
                }
             }
             return null;
          }
       }
    }

or use add/ExecuteBatch() appropriately for performance.

**Comment by shuyangzhou** [comment] 2016-03-04 16:30
@nitincchauhan the test in #590 is not sharing connection or statement across threads.

The connection is only used in main test thread. And we use it to create many different PreparedStatements. Then in the thread pool, each thread is using a different PreparedStatement. There is no connection or PreparedStatement shared among threads.

The real problem is the statement tracking from the com.zaxxer.hikari.pool.ProxyConnection, it links all com.zaxxer.hikari.pool.ProxyPreparedStatements back to the origin com.zaxxer.hikari.pool.ProxyConnection inexplicitly. Therefore causing different ProxyPreparedStatements can not be threadsafely used across threads.

The jdbs spec states clearly that closing connection must close all its opened statements, which means all drivers must have it already. Not sure why hikari must duplicate the implementation here.

We can take 2 possible solutions:
1) Make this statement tracking threadsafe
2) Drop of the statement tracking support, or at least make a switch for it that allows it to be turned off.

**Comment by brettwooldridge** [comment] 2016-03-05 05:43
I consider this to be a bug.  While statements should be prepared serially on a single connection , after that each statement should be independently accessible to a thread.  The Statement.close() path needs to be made thread safe, likely through synchronization of the untrack statement method.

**Comment by shuyangzhou** [comment] 2016-03-05 05:47
Thanks @brettwooldridge ! That is similar to the work around we are doing, synchronized on the connection when closing the statement. Hope to see your fixed release soon, then we will drop the work around.

**Comment by guidomedina** [comment] 2016-03-05 16:28
There might be faster alternatives than synchronizing; depending on the access pattern? MPSC or MPMC?

Check this project which has fast concurrent data structures, one example that could help here is:

https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/MpscArrayQueue.java

**Comment by brettwooldridge** [comment] 2016-03-06 00:47
This a typicaly an extremely low-contention path, in fact this kind of multi-threaded access is relatively rare (hence this issue going undiscovered despite 3 years of use by thousands of users).  The JIT's biased locking optimizations should remove most of the overhead of the lock in this case.

**Closed** 2016-03-06 00:49 UTC

**Comment by shuyangzhou** [comment] 2016-03-06 01:02
@brettwooldridge I think the trackStatement() and closeStatements() should be synced too.

1) While a thread is closing a statement, and other thread could use the connection to create a new statement, then trackStatement will race with untrackStatement().
2) A concurrent closing could happen on both the connection and statements, then the untrackStatement() will race with closeStatements().

**Comment by brettwooldridge** [comment] 2016-03-06 02:35
I don't mind to synchronize trackStatement(), but it is not valid to close statements while closing the connection.

**Comment by shuyangzhou** [comment] 2016-03-06 02:40
I am not saying it is on purposely to close connection and statements concurrently.

But it could happen, as long as the statements are handled to other threads, their lifecycles are out of  control.

**Comment by brettwooldridge** [comment] 2016-03-06 04:04
@shuyangzhou While I agree it is a theoretical race, I would consider that usage a coding error in the application.  Closing a connection while simultaneously closing statements is likely to lead to SQLException in many drivers anyway, because the driver cannot know there is a thread executing in a Statement it is likely to close the socket and therefore induce an exception in the thread executing the Statement.close().

**Comment by shuyangzhou** [comment] 2016-03-06 04:20
@brettwooldridge I do agree with you on it is not an expected usage, and even we sync on it, it won't fix everything.

But there is a slight difference here. If we do sync it, like you said one might get SQLException with error stack leading to the driver's classes. So most likely the developer will realize this a wrongful usage. Then he/she will start on digging and fixing it.

If we don't sync it, there is a chance that, in stead of failing at the driver, it fails on the concurrent modification to FastList first with an IndexOutOfBoundary exception with error stack leading to Hikari classes which could be very misleading. Then most likely they just file a bug report to you instead of starting to fix their own issues.

**Comment by brettwooldridge** [comment] 2016-03-06 08:41
@shuyangzhou Ok, I have added protection in the close path for closeStatements() and synchronized trackStatement().  There is still an unprotected code path that I will *not* change because it affects the hot-path performance too much; it is still possible to provoke thread-safety issues if statements are created while the connection is being closed.  But because this constitutes simultaneous thread access to the Connection it is considered by HikariCP to be invalid.

**Comment by shuyangzhou** [comment] 2016-03-06 22:57
Thanks @brettwooldridge !

**Comment by brettwooldridge** [comment] 2016-03-19 12:07
HikariCP 2.4.5 was been released with a fix for this issue.

**Comment by shuyangzhou** [comment] 2016-03-21 06:05
Thanks @brettwooldridge ! we will try it out :)

**Comment by kooroshvak** [comment] 2017-08-21 22:21
Getting similar exception with HikariCP version 2.6.3. I have studied this issue.  I am pretty sure my threads are not sharing the same connection at least directly. As a matter of fact, the exceptions happen when both are trying to return their current connection and get a new connection from the pool.  There are over 512 threads running on a 16 cores machine. Here are the two exceptions, the exceptions are coming from two different threads:

`Exception in thread "MainWorker-171" java.lang.ArrayIndexOutOfBoundsException: -1
	at com.zaxxer.hikari.util.FastList.remove(FastList.java:136)
	at com.zaxxer.hikari.pool.ProxyConnection.untrackStatement(ProxyConnection.java:169)
	at com.zaxxer.hikari.pool.ProxyStatement.close(ProxyStatement.java:70)
	at com.xxx.fsmon.summary.DirectorySummaryDAO.close(DirectorySummaryDAO.java:194)
	at com.xxx.fsmon.summary.DirectorySummaryDAO.renewConnectionToDb(DirectorySummaryDAO.java:159)
	at com.xxx.fsmon.directory.ThreadByDir.DirectoryRunnableExtractor.extract(DirectoryRunnableExtractor.java:215)
	at com.xxx.fsmon.directory.ThreadByDir.DirectoryRunnableExtractor.run(DirectoryRunnableExtractor.java:454)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

and

`[MainWorker-488] ERROR com.xxx.fsmon.summary.FileSummaryDAO: Could not prepare the statements!
java.lang.ArrayIndexOutOfBoundsException: -1
        at com.zaxxer.hikari.util.FastList.add(FastList.java:78)
        at com.zaxxer.hikari.pool.ProxyConnection.trackStatement(ProxyConnection.java:189)
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:312)
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
        at com.xxx.fsmon.summary.FileSummaryDAO.<init>(FileSummaryDAO.java:116)
        at com.xxx.fsmon.summary.DirectorySummaryDAO.renewConnectionToDb(DirectorySummaryDAO.java:171)
        at com.xxx.fsmon.directory.ThreadByDir.DirectoryRunnableExtractor.extract(DirectoryRunnableExtractor.java:215)
        at com.xxx.fsmon.directory.ThreadByDir.DirectoryRunnableExtractor.run(DirectoryRunnableExtractor.java:454) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

Could this be caused by a race condition where one thread closes a connection, but has not finished closing all its statements and the other thread somehow gets that connection and is trying to open a new prepareStatement on it?

I am going to synchronize my renewConnectionToDb() method and see if the exception goes away.

Any suggestion is greatly appreciated.
