### ISSUE TITLE
`FastList` implementation has no `iterator` method

### ISSUE THREAD

**Issue by koh-osug** [brettwooldridge/HikariCP#536] opened 2016-01-02 17:07 UTC
When using Hikari together with an Tomcat (correctly an embedded Tomcat running inside a Juni Test) Tomcat tries to find memory leaks. It is failing in Hikari because the `FastList` implementation has no `iterator` method.

```
Jan 02, 2016 6:03:13 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalsForLeaks
WARNUNG: Failed to check for ThreadLocal references for web application [/]
java.lang.UnsupportedOperationException
	at com.zaxxer.hikari.util.FastList.iterator(FastList.java:209)
	at org.apache.catalina.loader.WebappClassLoader.loadedByThisOrChild(WebappClassLoader.java:2621)
	at org.apache.catalina.loader.WebappClassLoader.checkThreadLocalMapForLeaks(WebappClassLoader.java:2539)
	at org.apache.catalina.loader.WebappClassLoader.checkThreadLocalsForLeaks(WebappClassLoader.java:2494)
	at org.apache.catalina.loader.WebappClassLoader.clearReferences(WebappClassLoader.java:2000)
	at org.apache.catalina.loader.WebappClassLoader.stop(WebappClassLoader.java:1906)
	at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:661)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5702)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1564)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by brettwooldridge** [comment] 2016-01-03 00:33
Duplicate of #495

**Closed by brettwooldridge** 2016-01-03 00:33 UTC
Labels: duplicate
