### ISSUE TITLE
Metrics exception

### ISSUE THREAD

**Issue by piechu** [brettwooldridge/HikariCP#238] opened 2015-01-22 16:23 UTC
I have noticed following behaviour when using HikariCP (version 2.2.5).

I have different DB users to connect to database so I'm using getConnection(username, password) from HikariDataSource. If I set MetricRegistry for HikariDataSource and run application - userA connected without problem, but when I wanted to get data for userB I got IllegalArgumentException:

java.lang.IllegalArgumentException: A metric named pool-name.pool.TotalConnections already exists
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91) ~[metrics-core-3.1.0.jar:3.1.0]
	at com.zaxxer.hikari.metrics.CodaHaleMetricsTracker.<init>(CodaHaleMetricsTracker.java:40) ~[HikariCP-2.2.5.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:143) ~[HikariCP-2.2.5.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:125) ~[HikariCP-2.2.5.jar:na]
	at ...

When I looked into HikariDataSource it seems that separate pools are created for different DB users, but when it comes to metrics - registration (in CodaHaleMetricsTracker) is done with the same pool name which cause exception to be thrown.

Do you have any suggestions how to use metrics in such scenario?

**Comment by brettwooldridge** [comment] 2015-01-23 14:56
This is a duplicate of #231.  Please follow the conversation there.  Because of issues like this, HikariCP 2.3.0 has deprecated the use of ``getConnection(username, password)``.  The recommened solution is to implement a wrapper ``DataSource`` that delegates to separate pool instances using the username or username/password tuple as a key.  In this way, the pools can be constructed with tailored ``HikariConfig``s that define a unique ``poolName`` for each instance.

**Closed by brettwooldridge** 2015-01-23 14:56 UTC

**Comment by dukejansen** [comment] 2019-02-13 21:08
I get a similar error in certain cases when I lose network connectivity, and the pool then re-initializes, and it tries to create the same metrics again, yielding the same stack trace. Any ideas on that one? Would it be possible to simply `remove` any previously registered metric under the same name before attempting to register the new ones?

I guess you already do this in the `CodaHaleMetricsTracker.close()` method, but somehow that's not getting called in this scenario. Maybe that's the real bug here, I don't know.

Looking over in the `BaseHikariPool.shutdown()` method, I see that at the very end there is indeed a call to `metricsTracker.close()`; however, there is no try/finally leading up to it. This suggests maybe a non-graceful close due to, say, a network connection dying, could yield a case where the pool was shutdown, but the metric is left alive.

If so, it seems like it would be a pretty easy fix to just guarantee the call to `metricsTracker.close()`.

@brettwooldridge let me know if you think I should open a new ticket or what. I could probably produce a PR if you want.

**Comment by brettwooldridge** [comment] 2019-02-20 17:14
@dukejansen What version of HikariCP are you experiencing this issue on?  Maybe open a new issue, rather than continuing on this closed one...
